# Generated by Django 4.2.16 on 2026-08-22 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadCapturePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField()),
                ("qr_record_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("headline", models.CharField(blank=True, max_length=500, null=True)),
                ("subheadline", models.TextField(blank=True, null=True)),
                ("hero_image", models.TextField(blank=True, null=True)),
                ("button_text", models.CharField(default="Submit", max_length=100)),
                ("button_color", models.CharField(default="#8B5CF6", max_length=7)),
                ("background_color", models.CharField(default="#09090B", max_length=7)),
                ("text_color", models.CharField(default="#FAFAFA", max_length=7)),
                (
                    "thank_you_message",
                    models.TextField(default="Thank you for signing up!"),
                ),
                ("redirect_url", models.TextField(blank=True, null=True)),
                ("form_fields", models.TextField(default="[]")),
                ("is_active", models.BooleanField(default=True)),
                ("requires_opt_in", models.BooleanField(default=False)),
                ("privacy_policy", models.TextField(blank=True, null=True)),
                ("consent_text", models.TextField(blank=True, null=True)),
                ("views", models.IntegerField(default=0)),
                ("submissions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead_capture_pages",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QRFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qr_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField()),
                ("filename", models.CharField(max_length=255)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.BigIntegerField(default=0, null=True)),
                ("s3_bucket", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_key", models.TextField()),
                ("s3_url", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "qr_files",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QRRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                ("folder_id", models.UUIDField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("qr_type", models.CharField(default="url", max_length=50, null=True)),
                ("qr_type_id", models.CharField(blank=True, max_length=50, null=True)),
                ("size", models.BigIntegerField(default=256, null=True)),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("is_dynamic", models.BooleanField(default=False, null=True)),
                ("redirect_url", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict, null=True)),
                ("customization", models.JSONField(default=dict, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("max_scans", models.BigIntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("geo_restrictions", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scan_count", models.BigIntegerField(default=0, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "qr_records",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                (
                    "plan",
                    models.CharField(
                        blank=True, default="free", max_length=20, null=True
                    ),
                ),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("api_calls_today", models.BigIntegerField(default=0, null=True)),
                ("api_calls_reset_at", models.DateField(blank=True, null=True)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("default_workspace_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField()),
                ("url", models.TextField()),
                ("secret", models.CharField(blank=True, max_length=64, null=True)),
                ("events", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("fail_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "webhooks",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("plan", models.CharField(default="free", max_length=20, null=True)),
                ("max_members", models.BigIntegerField(default=1, null=True)),
                ("max_qr_codes", models.BigIntegerField(default=50, null=True)),
                ("max_folders", models.BigIntegerField(default=5, null=True)),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "brand_color",
                    models.CharField(default="#8B5CF6", max_length=7, null=True),
                ),
                ("brand_logo", models.TextField(blank=True, null=True)),
                ("favicon_url", models.TextField(blank=True, null=True)),
                ("custom_css", models.TextField(blank=True, null=True)),
                ("remove_branding", models.BooleanField(default=False, null=True)),
                ("custom_footer", models.TextField(blank=True, null=True)),
                ("sso_enabled", models.BooleanField(default=False, null=True)),
                (
                    "sso_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sso_config", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "workspaces",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("role", models.CharField(default="viewer", max_length=20)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("invited_by", models.UUIDField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_invites",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("payload", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField(default=0)),
                ("response", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("duration", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        db_column="webhook_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api.webhook",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QRScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("device_type", models.CharField(blank=True, max_length=20, null=True)),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                ("os_version", models.CharField(blank=True, max_length=20, null=True)),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "qr_record",
                    models.ForeignKey(
                        db_column="qr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="api.qrrecord",
                    ),
                ),
            ],
            options={
                "db_table": "qr_scans",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="qrrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_records",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.TextField()),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("opted_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        db_column="page_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="api.leadcapturepage",
                    ),
                ),
            ],
            options={
                "db_table": "leads",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FreeTierUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("session_id", models.CharField(blank=True, max_length=64, null=True)),
                ("qr_count", models.BigIntegerField(default=0, null=True)),
                ("date", models.DateField(null=True)),
                ("first_used", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "free_tier_usages",
                "managed": True,
                "unique_together": {("ip_address", "date")},
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="#8B5CF6", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("qr_count", models.IntegerField(default=0)),
                ("scan_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "folders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField()),
                ("action", models.CharField(max_length=50)),
                ("resource", models.CharField(max_length=50)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(default="viewer", max_length=20)),
                ("invited_by", models.UUIDField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to="api.user",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_members",
                "managed": True,
                "unique_together": {("workspace", "user")},
            },
        ),
    ]
