# Generated by Django 4.2.16 on 2026-10-03 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_loginattempt_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_usable_password",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "oauth_accounts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AuthHandoffCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("provider", models.CharField(max_length=20)),
                ("next_path", models.CharField(default="/dashboard", max_length=512)),
                ("is_new_user", models.BooleanField(default=False)),
                ("password_reset", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_handoff_codes",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "auth_handoff_codes",
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="oauth_accounts_provider_uid_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="oauth_accounts_user_provider_uniq"
            ),
        ),
    ]
