// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const breakdownRollup = `-- name: BreakdownRollup :many
SELECT key, sum(scans)::bigint AS scans, sum(unique_scans)::bigint AS unique_scans
FROM scan_stats_daily_dim
WHERE workspace_id = $1
  AND dimension = $2
  AND day >= ($3::timestamptz AT TIME ZONE 'UTC')::date
  AND day <= (($4::timestamptz - interval '1 microsecond') AT TIME ZONE 'UTC')::date
  AND ($5::uuid[] IS NULL OR qr_code_id = ANY($5::uuid[]))
GROUP BY key
ORDER BY scans DESC
LIMIT 20
`

type BreakdownRollupParams struct {
	Ws        uuid.UUID   `json:"ws"`
	Dimension string      `json:"dimension"`
	FromTs    time.Time   `json:"from_ts"`
	ToTs      time.Time   `json:"to_ts"`
	QrIds     []uuid.UUID `json:"qr_ids"`
}

type BreakdownRollupRow struct {
	Key         string `json:"key"`
	Scans       int64  `json:"scans"`
	UniqueScans int64  `json:"unique_scans"`
}

// Ranges >= 3 days: UTC-day dimension rollups (edge days approximate by < 1 day of data).
func (q *Queries) BreakdownRollup(ctx context.Context, arg BreakdownRollupParams) ([]BreakdownRollupRow, error) {
	rows, err := q.db.Query(ctx, breakdownRollup,
		arg.Ws,
		arg.Dimension,
		arg.FromTs,
		arg.ToTs,
		arg.QrIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakdownRollupRow{}
	for rows.Next() {
		var i BreakdownRollupRow
		if err := rows.Scan(&i.Key, &i.Scans, &i.UniqueScans); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heatmap = `-- name: Heatmap :many
SELECT extract(isodow FROM bucket_start AT TIME ZONE $1::text)::int AS weekday,
       extract(hour   FROM bucket_start AT TIME ZONE $1::text)::int AS hour_of_day,
       sum(scans)::bigint AS scans
FROM scan_stats_15m
WHERE workspace_id = $2
  AND bucket_start >= $3 AND bucket_start < $4
  AND ($5::uuid[] IS NULL OR qr_code_id = ANY($5::uuid[]))
GROUP BY 1, 2
`

type HeatmapParams struct {
	Tz     string      `json:"tz"`
	Ws     uuid.UUID   `json:"ws"`
	FromTs time.Time   `json:"from_ts"`
	ToTs   time.Time   `json:"to_ts"`
	QrIds  []uuid.UUID `json:"qr_ids"`
}

type HeatmapRow struct {
	Weekday   int32 `json:"weekday"`
	HourOfDay int32 `json:"hour_of_day"`
	Scans     int64 `json:"scans"`
}

// Weekday (1=Mon..7=Sun) x local hour-of-day.
func (q *Queries) Heatmap(ctx context.Context, arg HeatmapParams) ([]HeatmapRow, error) {
	rows, err := q.db.Query(ctx, heatmap,
		arg.Tz,
		arg.Ws,
		arg.FromTs,
		arg.ToTs,
		arg.QrIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeatmapRow{}
	for rows.Next() {
		var i HeatmapRow
		if err := rows.Scan(&i.Weekday, &i.HourOfDay, &i.Scans); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryTotals = `-- name: SummaryTotals :one

SELECT COALESCE(sum(scans),0)::bigint        AS scans,
       COALESCE(sum(unique_scans),0)::bigint AS unique_scans,
       COALESCE(sum(bot_hits),0)::bigint     AS bot_hits,
       COALESCE(sum(blocked_hits),0)::bigint AS blocked_hits
FROM scan_stats_15m
WHERE workspace_id = $1
  AND bucket_start >= $2 AND bucket_start < $3
  AND ($4::uuid[] IS NULL OR qr_code_id = ANY($4::uuid[]))
  AND ($5::uuid IS NULL OR campaign_id = $5::uuid)
`

type SummaryTotalsParams struct {
	Ws       uuid.UUID   `json:"ws"`
	FromTs   time.Time   `json:"from_ts"`
	ToTs     time.Time   `json:"to_ts"`
	QrIds    []uuid.UUID `json:"qr_ids"`
	Campaign pgtype.UUID `json:"campaign"`
}

type SummaryTotalsRow struct {
	Scans       int64 `json:"scans"`
	UniqueScans int64 `json:"unique_scans"`
	BotHits     int64 `json:"bot_hits"`
	BlockedHits int64 `json:"blocked_hits"`
}

// =====================================================================
// Analytics read queries (sqlc, internal/analytics/queries.sql).
// Parameters: $ws workspace id, $from/$to timestamptz (half-open [from,to)),
// $tz IANA zone, $qr uuid[] (NULL = all), $campaign uuid (NULL = all).
// All ranges are computed in the viewer's timezone by the API and passed as
// UTC instants aligned to local midnight.
// =====================================================================
func (q *Queries) SummaryTotals(ctx context.Context, arg SummaryTotalsParams) (SummaryTotalsRow, error) {
	row := q.db.QueryRow(ctx, summaryTotals,
		arg.Ws,
		arg.FromTs,
		arg.ToTs,
		arg.QrIds,
		arg.Campaign,
	)
	var i SummaryTotalsRow
	err := row.Scan(
		&i.Scans,
		&i.UniqueScans,
		&i.BotHits,
		&i.BlockedHits,
	)
	return i, err
}

const timeseriesDaily = `-- name: TimeseriesDaily :many
WITH series AS (
    SELECT generate_series(
             ($2::timestamptz AT TIME ZONE $1::text)::date,
             (($3::timestamptz - interval '1 microsecond') AT TIME ZONE $1::text)::date,
             interval '1 day')::date AS day
), agg AS (
    SELECT (bucket_start AT TIME ZONE $1::text)::date AS day,
           sum(scans) AS scans, sum(unique_scans) AS unique_scans
    FROM scan_stats_15m
    WHERE workspace_id = $4
      AND bucket_start >= $2 AND bucket_start < $3
      AND ($5::uuid[] IS NULL OR qr_code_id = ANY($5::uuid[]))
      AND ($6::uuid IS NULL OR campaign_id = $6::uuid)
    GROUP BY 1
)
SELECT s.day, COALESCE(a.scans,0)::bigint AS scans, COALESCE(a.unique_scans,0)::bigint AS unique_scans
FROM series s LEFT JOIN agg a USING (day)
ORDER BY s.day
`

type TimeseriesDailyParams struct {
	Tz       string      `json:"tz"`
	FromTs   time.Time   `json:"from_ts"`
	ToTs     time.Time   `json:"to_ts"`
	Ws       uuid.UUID   `json:"ws"`
	QrIds    []uuid.UUID `json:"qr_ids"`
	Campaign pgtype.UUID `json:"campaign"`
}

type TimeseriesDailyRow struct {
	Day         pgtype.Date `json:"day"`
	Scans       int64       `json:"scans"`
	UniqueScans int64       `json:"unique_scans"`
}

// Zero-filled local-day series.
func (q *Queries) TimeseriesDaily(ctx context.Context, arg TimeseriesDailyParams) ([]TimeseriesDailyRow, error) {
	rows, err := q.db.Query(ctx, timeseriesDaily,
		arg.Tz,
		arg.FromTs,
		arg.ToTs,
		arg.Ws,
		arg.QrIds,
		arg.Campaign,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeseriesDailyRow{}
	for rows.Next() {
		var i TimeseriesDailyRow
		if err := rows.Scan(&i.Day, &i.Scans, &i.UniqueScans); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topQRCodes = `-- name: TopQRCodes :many
SELECT q.id, q.name, q.short_code,
       COALESCE(sum(s.scans),0)::bigint AS scans,
       COALESCE(sum(s.unique_scans),0)::bigint AS unique_scans
FROM qr_codes q
LEFT JOIN scan_stats_15m s ON s.qr_code_id = q.id
  AND s.bucket_start >= $1 AND s.bucket_start < $2
WHERE q.workspace_id = $3
GROUP BY q.id, q.name, q.short_code
ORDER BY scans DESC
LIMIT 10
`

type TopQRCodesParams struct {
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
	Ws     uuid.UUID `json:"ws"`
}

type TopQRCodesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	ShortCode   *string   `json:"short_code"`
	Scans       int64     `json:"scans"`
	UniqueScans int64     `json:"unique_scans"`
}

func (q *Queries) TopQRCodes(ctx context.Context, arg TopQRCodesParams) ([]TopQRCodesRow, error) {
	rows, err := q.db.Query(ctx, topQRCodes, arg.FromTs, arg.ToTs, arg.Ws)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopQRCodesRow{}
	for rows.Next() {
		var i TopQRCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortCode,
			&i.Scans,
			&i.UniqueScans,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
