// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (id, workspace_id, hostname, verification_token, root_redirect_url, not_found_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at
`

type CreateDomainParams struct {
	ID                uuid.UUID   `json:"id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	Hostname          string      `json:"hostname"`
	VerificationToken string      `json:"verification_token"`
	RootRedirectUrl   *string     `json:"root_redirect_url"`
	NotFoundUrl       *string     `json:"not_found_url"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.WorkspaceID,
		arg.Hostname,
		arg.VerificationToken,
		arg.RootRedirectUrl,
		arg.NotFoundUrl,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.ProviderHostnameID,
		&i.TlsStatus,
		&i.RootRedirectUrl,
		&i.NotFoundUrl,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1 AND workspace_id = $2
`

type DeleteDomainParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.WorkspaceID)
	return err
}

const ensurePlatformDomain = `-- name: EnsurePlatformDomain :one
INSERT INTO domains (id, workspace_id, hostname, status, verification_token, tls_status, verified_at)
VALUES ($1, NULL, $2, 'active', 'platform', 'active', now())
ON CONFLICT (hostname) DO UPDATE SET hostname = EXCLUDED.hostname
RETURNING id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at
`

type EnsurePlatformDomainParams struct {
	ID       uuid.UUID `json:"id"`
	Hostname string    `json:"hostname"`
}

func (q *Queries) EnsurePlatformDomain(ctx context.Context, arg EnsurePlatformDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, ensurePlatformDomain, arg.ID, arg.Hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.ProviderHostnameID,
		&i.TlsStatus,
		&i.RootRedirectUrl,
		&i.NotFoundUrl,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at FROM domains
WHERE hostname = $1
`

func (q *Queries) GetDomainByHostname(ctx context.Context, hostname string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostname, hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.ProviderHostnameID,
		&i.TlsStatus,
		&i.RootRedirectUrl,
		&i.NotFoundUrl,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at FROM domains
WHERE id = $1
`

func (q *Queries) GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.ProviderHostnameID,
		&i.TlsStatus,
		&i.RootRedirectUrl,
		&i.NotFoundUrl,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDomains = `-- name: ListActiveDomains :many
SELECT id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at FROM domains
WHERE status = 'active'
`

func (q *Queries) ListActiveDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.ProviderHostnameID,
			&i.TlsStatus,
			&i.RootRedirectUrl,
			&i.NotFoundUrl,
			&i.LastCheckedAt,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForWorkspace = `-- name: ListDomainsForWorkspace :many
SELECT id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at FROM domains
WHERE workspace_id = $1 OR workspace_id IS NULL
ORDER BY created_at
`

func (q *Queries) ListDomainsForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.ProviderHostnameID,
			&i.TlsStatus,
			&i.RootRedirectUrl,
			&i.NotFoundUrl,
			&i.LastCheckedAt,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomainStatus = `-- name: UpdateDomainStatus :one
UPDATE domains
SET status = $2, tls_status = $3, verified_at = COALESCE($4, verified_at), last_checked_at = now()
WHERE id = $1
RETURNING id, workspace_id, hostname, status, verification_token, provider_hostname_id, tls_status, root_redirect_url, not_found_url, last_checked_at, verified_at, created_at
`

type UpdateDomainStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	TlsStatus  string             `json:"tls_status"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainStatus,
		arg.ID,
		arg.Status,
		arg.TlsStatus,
		arg.VerifiedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.ProviderHostnameID,
		&i.TlsStatus,
		&i.RootRedirectUrl,
		&i.NotFoundUrl,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
