// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AbuseReport struct {
	ID               uuid.UUID          `json:"id"`
	QrCodeID         pgtype.UUID        `json:"qr_code_id"`
	Hostname         string             `json:"hostname"`
	ShortCode        string             `json:"short_code"`
	Reason           string             `json:"reason"`
	Details          *string            `json:"details"`
	ReporterEmail    *string            `json:"reporter_email"`
	ReporterIpPrefix *string            `json:"reporter_ip_prefix"`
	Status           string             `json:"status"`
	ResolvedBy       pgtype.UUID        `json:"resolved_by"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type ApiKey struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	KeyHash     []byte             `json:"key_hash"`
	Scopes      []string           `json:"scopes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type AuditLog struct {
	ID          int64           `json:"id"`
	WorkspaceID pgtype.UUID     `json:"workspace_id"`
	ActorType   string          `json:"actor_type"`
	ActorID     pgtype.UUID     `json:"actor_id"`
	Action      string          `json:"action"`
	TargetType  string          `json:"target_type"`
	TargetID    pgtype.UUID     `json:"target_id"`
	Changes     json.RawMessage `json:"changes"`
	IpPrefix    *string         `json:"ip_prefix"`
	UserAgent   *string         `json:"user_agent"`
	RequestID   *string         `json:"request_id"`
	CreatedAt   time.Time       `json:"created_at"`
}

type BillingEvent struct {
	ID              uuid.UUID          `json:"id"`
	Provider        string             `json:"provider"`
	ProviderEventID string             `json:"provider_event_id"`
	Type            string             `json:"type"`
	Payload         json.RawMessage    `json:"payload"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type Campaign struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	GoalScans   *int64             `json:"goal_scans"`
	Utm         json.RawMessage    `json:"utm"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Domain struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Hostname           string             `json:"hostname"`
	Status             string             `json:"status"`
	VerificationToken  string             `json:"verification_token"`
	ProviderHostnameID *string            `json:"provider_hostname_id"`
	TlsStatus          string             `json:"tls_status"`
	RootRedirectUrl    *string            `json:"root_redirect_url"`
	NotFoundUrl        *string            `json:"not_found_url"`
	LastCheckedAt      pgtype.Timestamptz `json:"last_checked_at"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedAt          time.Time          `json:"created_at"`
}

type EmailToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type File struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Purpose     string             `json:"purpose"`
	StorageKey  string             `json:"storage_key"`
	MimeType    string             `json:"mime_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Sha256      []byte             `json:"sha256"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Folder struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type IdempotencyKey struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Key          string    `json:"key"`
	Method       string    `json:"method"`
	Path         string    `json:"path"`
	RequestHash  []byte    `json:"request_hash"`
	StatusCode   *int32    `json:"status_code"`
	ResponseBody []byte    `json:"response_body"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type Invite struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	TokenHash   []byte             `json:"token_hash"`
	InvitedBy   uuid.UUID          `json:"invited_by"`
	ExpiresAt   time.Time          `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Job struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	Kind         string             `json:"kind"`
	Status       string             `json:"status"`
	InputFileID  pgtype.UUID        `json:"input_file_id"`
	OutputFileID pgtype.UUID        `json:"output_file_id"`
	Params       json.RawMessage    `json:"params"`
	Total        int32              `json:"total"`
	Processed    int32              `json:"processed"`
	Failed       int32              `json:"failed"`
	Errors       json.RawMessage    `json:"errors"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type OauthAccount struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type QrCode struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Mode             string             `json:"mode"`
	ContentType      string             `json:"content_type"`
	Name             string             `json:"name"`
	DomainID         pgtype.UUID        `json:"domain_id"`
	ShortCode        *string            `json:"short_code"`
	LegacyShortCode  *string            `json:"legacy_short_code"`
	Gs1Gtin          *string            `json:"gs1_gtin"`
	StaticPayload    *string            `json:"static_payload"`
	StaticContent    []byte             `json:"static_content"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	Design           json.RawMessage    `json:"design"`
	DesignHash       []byte             `json:"design_hash"`
	TemplateID       pgtype.UUID        `json:"template_id"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	Status           string             `json:"status"`
	IsReadOnly       bool               `json:"is_read_only"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ScanLimit        *int64             `json:"scan_limit"`
	PasswordHash     *string            `json:"password_hash"`
	FallbackUrl      *string            `json:"fallback_url"`
	SafetyStatus     string             `json:"safety_status"`
	TotalScans       int64              `json:"total_scans"`
	UniqueScans      int64              `json:"unique_scans"`
	LastScannedAt    pgtype.Timestamptz `json:"last_scanned_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type QrCodeTag struct {
	QrCodeID uuid.UUID `json:"qr_code_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

type QrVersion struct {
	ID              uuid.UUID       `json:"id"`
	QrCodeID        uuid.UUID       `json:"qr_code_id"`
	VersionNo       int32           `json:"version_no"`
	DestinationKind string          `json:"destination_kind"`
	DestinationUrl  *string         `json:"destination_url"`
	HostedPage      []byte          `json:"hosted_page"`
	Rules           json.RawMessage `json:"rules"`
	Utm             json.RawMessage `json:"utm"`
	EffectiveAt     time.Time       `json:"effective_at"`
	SafetyStatus    string          `json:"safety_status"`
	RestoredFrom    pgtype.UUID     `json:"restored_from"`
	ChangeNote      *string         `json:"change_note"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
	CreatedByKey    pgtype.UUID     `json:"created_by_key"`
	CreatedAt       time.Time       `json:"created_at"`
}

type ScanEvent struct {
	EventID        uuid.UUID   `json:"event_id"`
	OccurredAt     time.Time   `json:"occurred_at"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	QrCodeID       uuid.UUID   `json:"qr_code_id"`
	VersionID      pgtype.UUID `json:"version_id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	DomainID       uuid.UUID   `json:"domain_id"`
	RuleID         *string     `json:"rule_id"`
	Outcome        string      `json:"outcome"`
	Method         string      `json:"method"`
	IsBot          bool        `json:"is_bot"`
	BotReason      *string     `json:"bot_reason"`
	IsDuplicate    bool        `json:"is_duplicate"`
	IsUnique       bool        `json:"is_unique"`
	VisitorHash    []byte      `json:"visitor_hash"`
	DeviceType     *string     `json:"device_type"`
	Os             *string     `json:"os"`
	OsVersion      *string     `json:"os_version"`
	Browser        *string     `json:"browser"`
	BrowserVersion *string     `json:"browser_version"`
	Country        *string     `json:"country"`
	Region         *string     `json:"region"`
	City           *string     `json:"city"`
	Language       *string     `json:"language"`
	ReferrerHost   *string     `json:"referrer_host"`
	UtmSource      *string     `json:"utm_source"`
	UtmMedium      *string     `json:"utm_medium"`
	UtmCampaign    *string     `json:"utm_campaign"`
}

type ScanEvents202609 struct {
	EventID        uuid.UUID   `json:"event_id"`
	OccurredAt     time.Time   `json:"occurred_at"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	QrCodeID       uuid.UUID   `json:"qr_code_id"`
	VersionID      pgtype.UUID `json:"version_id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	DomainID       uuid.UUID   `json:"domain_id"`
	RuleID         *string     `json:"rule_id"`
	Outcome        string      `json:"outcome"`
	Method         string      `json:"method"`
	IsBot          bool        `json:"is_bot"`
	BotReason      *string     `json:"bot_reason"`
	IsDuplicate    bool        `json:"is_duplicate"`
	IsUnique       bool        `json:"is_unique"`
	VisitorHash    []byte      `json:"visitor_hash"`
	DeviceType     *string     `json:"device_type"`
	Os             *string     `json:"os"`
	OsVersion      *string     `json:"os_version"`
	Browser        *string     `json:"browser"`
	BrowserVersion *string     `json:"browser_version"`
	Country        *string     `json:"country"`
	Region         *string     `json:"region"`
	City           *string     `json:"city"`
	Language       *string     `json:"language"`
	ReferrerHost   *string     `json:"referrer_host"`
	UtmSource      *string     `json:"utm_source"`
	UtmMedium      *string     `json:"utm_medium"`
	UtmCampaign    *string     `json:"utm_campaign"`
}

type ScanEvents202610 struct {
	EventID        uuid.UUID   `json:"event_id"`
	OccurredAt     time.Time   `json:"occurred_at"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	QrCodeID       uuid.UUID   `json:"qr_code_id"`
	VersionID      pgtype.UUID `json:"version_id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	DomainID       uuid.UUID   `json:"domain_id"`
	RuleID         *string     `json:"rule_id"`
	Outcome        string      `json:"outcome"`
	Method         string      `json:"method"`
	IsBot          bool        `json:"is_bot"`
	BotReason      *string     `json:"bot_reason"`
	IsDuplicate    bool        `json:"is_duplicate"`
	IsUnique       bool        `json:"is_unique"`
	VisitorHash    []byte      `json:"visitor_hash"`
	DeviceType     *string     `json:"device_type"`
	Os             *string     `json:"os"`
	OsVersion      *string     `json:"os_version"`
	Browser        *string     `json:"browser"`
	BrowserVersion *string     `json:"browser_version"`
	Country        *string     `json:"country"`
	Region         *string     `json:"region"`
	City           *string     `json:"city"`
	Language       *string     `json:"language"`
	ReferrerHost   *string     `json:"referrer_host"`
	UtmSource      *string     `json:"utm_source"`
	UtmMedium      *string     `json:"utm_medium"`
	UtmCampaign    *string     `json:"utm_campaign"`
}

type ScanEvents202611 struct {
	EventID        uuid.UUID   `json:"event_id"`
	OccurredAt     time.Time   `json:"occurred_at"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	QrCodeID       uuid.UUID   `json:"qr_code_id"`
	VersionID      pgtype.UUID `json:"version_id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	DomainID       uuid.UUID   `json:"domain_id"`
	RuleID         *string     `json:"rule_id"`
	Outcome        string      `json:"outcome"`
	Method         string      `json:"method"`
	IsBot          bool        `json:"is_bot"`
	BotReason      *string     `json:"bot_reason"`
	IsDuplicate    bool        `json:"is_duplicate"`
	IsUnique       bool        `json:"is_unique"`
	VisitorHash    []byte      `json:"visitor_hash"`
	DeviceType     *string     `json:"device_type"`
	Os             *string     `json:"os"`
	OsVersion      *string     `json:"os_version"`
	Browser        *string     `json:"browser"`
	BrowserVersion *string     `json:"browser_version"`
	Country        *string     `json:"country"`
	Region         *string     `json:"region"`
	City           *string     `json:"city"`
	Language       *string     `json:"language"`
	ReferrerHost   *string     `json:"referrer_host"`
	UtmSource      *string     `json:"utm_source"`
	UtmMedium      *string     `json:"utm_medium"`
	UtmCampaign    *string     `json:"utm_campaign"`
}

type ScanEventsDefault struct {
	EventID        uuid.UUID   `json:"event_id"`
	OccurredAt     time.Time   `json:"occurred_at"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	QrCodeID       uuid.UUID   `json:"qr_code_id"`
	VersionID      pgtype.UUID `json:"version_id"`
	CampaignID     pgtype.UUID `json:"campaign_id"`
	DomainID       uuid.UUID   `json:"domain_id"`
	RuleID         *string     `json:"rule_id"`
	Outcome        string      `json:"outcome"`
	Method         string      `json:"method"`
	IsBot          bool        `json:"is_bot"`
	BotReason      *string     `json:"bot_reason"`
	IsDuplicate    bool        `json:"is_duplicate"`
	IsUnique       bool        `json:"is_unique"`
	VisitorHash    []byte      `json:"visitor_hash"`
	DeviceType     *string     `json:"device_type"`
	Os             *string     `json:"os"`
	OsVersion      *string     `json:"os_version"`
	Browser        *string     `json:"browser"`
	BrowserVersion *string     `json:"browser_version"`
	Country        *string     `json:"country"`
	Region         *string     `json:"region"`
	City           *string     `json:"city"`
	Language       *string     `json:"language"`
	ReferrerHost   *string     `json:"referrer_host"`
	UtmSource      *string     `json:"utm_source"`
	UtmMedium      *string     `json:"utm_medium"`
	UtmCampaign    *string     `json:"utm_campaign"`
}

type ScanStats15m struct {
	QrCodeID    uuid.UUID   `json:"qr_code_id"`
	BucketStart time.Time   `json:"bucket_start"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	Scans       int32       `json:"scans"`
	UniqueScans int32       `json:"unique_scans"`
	BotHits     int32       `json:"bot_hits"`
	BlockedHits int32       `json:"blocked_hits"`
}

type ScanStatsDailyDim struct {
	QrCodeID    uuid.UUID   `json:"qr_code_id"`
	Day         pgtype.Date `json:"day"`
	Dimension   string      `json:"dimension"`
	Key         string      `json:"key"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	Scans       int32       `json:"scans"`
	UniqueScans int32       `json:"unique_scans"`
}

type ScanVisitorsDaily struct {
	QrCodeID    uuid.UUID   `json:"qr_code_id"`
	Day         pgtype.Date `json:"day"`
	VisitorHash []byte      `json:"visitor_hash"`
	FirstSeenAt time.Time   `json:"first_seen_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	FamilyID         uuid.UUID          `json:"family_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	UserAgent        *string            `json:"user_agent"`
	IpPrefix         *string            `json:"ip_prefix"`
	CreatedAt        time.Time          `json:"created_at"`
	LastUsedAt       time.Time          `json:"last_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy       pgtype.UUID        `json:"replaced_by"`
}

type ShortCodeTombstone struct {
	DomainID  uuid.UUID `json:"domain_id"`
	ShortCode string    `json:"short_code"`
	PurgedAt  time.Time `json:"purged_at"`
}

type Subscription struct {
	ID                     uuid.UUID          `json:"id"`
	WorkspaceID            uuid.UUID          `json:"workspace_id"`
	Provider               string             `json:"provider"`
	ProviderCustomerID     string             `json:"provider_customer_id"`
	ProviderSubscriptionID string             `json:"provider_subscription_id"`
	PlanID                 string             `json:"plan_id"`
	BillingInterval        string             `json:"billing_interval"`
	Status                 string             `json:"status"`
	Seats                  int32              `json:"seats"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd      bool               `json:"cancel_at_period_end"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type Tag struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
}

type Template struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Name        string          `json:"name"`
	Design      json.RawMessage `json:"design"`
	IsLocked    bool            `json:"is_locked"`
	IsDefault   bool            `json:"is_default"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    *string            `json:"password_hash"`
	Name            string             `json:"name"`
	AvatarUrl       *string            `json:"avatar_url"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	IsStaff         bool               `json:"is_staff"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Webhook struct {
	ID                  uuid.UUID   `json:"id"`
	WorkspaceID         uuid.UUID   `json:"workspace_id"`
	Url                 string      `json:"url"`
	SecretCiphertext    []byte      `json:"secret_ciphertext"`
	Events              []string    `json:"events"`
	IsActive            bool        `json:"is_active"`
	ConsecutiveFailures int32       `json:"consecutive_failures"`
	DisabledReason      *string     `json:"disabled_reason"`
	CreatedBy           pgtype.UUID `json:"created_by"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	WebhookID      uuid.UUID          `json:"webhook_id"`
	EventID        uuid.UUID          `json:"event_id"`
	EventType      string             `json:"event_type"`
	Payload        json.RawMessage    `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	LastStatusCode *int32             `json:"last_status_code"`
	LastError      *string            `json:"last_error"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type Workspace struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	OwnerID         uuid.UUID          `json:"owner_id"`
	PlanID          string             `json:"plan_id"`
	Timezone        string             `json:"timezone"`
	DefaultDomainID pgtype.UUID        `json:"default_domain_id"`
	Brand           json.RawMessage    `json:"brand"`
	Settings        json.RawMessage    `json:"settings"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
