// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qr.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveDynamicQRCodes = `-- name: CountActiveDynamicQRCodes :one
SELECT count(*)::int FROM qr_codes
WHERE workspace_id = $1 AND mode = 'dynamic' AND deleted_at IS NULL
`

func (q *Queries) CountActiveDynamicQRCodes(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveDynamicQRCodes, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createQRCode = `-- name: CreateQRCode :one
INSERT INTO qr_codes (
    id, workspace_id, domain_id, short_code, mode, content_type,
    name, status, design, design_hash, static_payload, static_content
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, created_by, mode, content_type, name, domain_id, short_code, legacy_short_code, gs1_gtin, static_payload, static_content, current_version_id, design, design_hash, template_id, folder_id, campaign_id, status, is_read_only, starts_at, expires_at, scan_limit, password_hash, fallback_url, safety_status, total_scans, unique_scans, last_scanned_at, created_at, updated_at, archived_at, deleted_at
`

type CreateQRCodeParams struct {
	ID            uuid.UUID       `json:"id"`
	WorkspaceID   uuid.UUID       `json:"workspace_id"`
	DomainID      pgtype.UUID     `json:"domain_id"`
	ShortCode     *string         `json:"short_code"`
	Mode          string          `json:"mode"`
	ContentType   string          `json:"content_type"`
	Name          string          `json:"name"`
	Status        string          `json:"status"`
	Design        json.RawMessage `json:"design"`
	DesignHash    []byte          `json:"design_hash"`
	StaticPayload *string         `json:"static_payload"`
	StaticContent []byte          `json:"static_content"`
}

func (q *Queries) CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, createQRCode,
		arg.ID,
		arg.WorkspaceID,
		arg.DomainID,
		arg.ShortCode,
		arg.Mode,
		arg.ContentType,
		arg.Name,
		arg.Status,
		arg.Design,
		arg.DesignHash,
		arg.StaticPayload,
		arg.StaticContent,
	)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Mode,
		&i.ContentType,
		&i.Name,
		&i.DomainID,
		&i.ShortCode,
		&i.LegacyShortCode,
		&i.Gs1Gtin,
		&i.StaticPayload,
		&i.StaticContent,
		&i.CurrentVersionID,
		&i.Design,
		&i.DesignHash,
		&i.TemplateID,
		&i.FolderID,
		&i.CampaignID,
		&i.Status,
		&i.IsReadOnly,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ScanLimit,
		&i.PasswordHash,
		&i.FallbackUrl,
		&i.SafetyStatus,
		&i.TotalScans,
		&i.UniqueScans,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createQRVersion = `-- name: CreateQRVersion :one
INSERT INTO qr_versions (
    id, qr_code_id, version_no, destination_kind, destination_url,
    hosted_page, rules, utm, effective_at, change_note, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, qr_code_id, version_no, destination_kind, destination_url, hosted_page, rules, utm, effective_at, safety_status, restored_from, change_note, created_by, created_by_key, created_at
`

type CreateQRVersionParams struct {
	ID              uuid.UUID       `json:"id"`
	QrCodeID        uuid.UUID       `json:"qr_code_id"`
	VersionNo       int32           `json:"version_no"`
	DestinationKind string          `json:"destination_kind"`
	DestinationUrl  *string         `json:"destination_url"`
	HostedPage      []byte          `json:"hosted_page"`
	Rules           json.RawMessage `json:"rules"`
	Utm             json.RawMessage `json:"utm"`
	EffectiveAt     time.Time       `json:"effective_at"`
	ChangeNote      *string         `json:"change_note"`
	CreatedBy       pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateQRVersion(ctx context.Context, arg CreateQRVersionParams) (QrVersion, error) {
	row := q.db.QueryRow(ctx, createQRVersion,
		arg.ID,
		arg.QrCodeID,
		arg.VersionNo,
		arg.DestinationKind,
		arg.DestinationUrl,
		arg.HostedPage,
		arg.Rules,
		arg.Utm,
		arg.EffectiveAt,
		arg.ChangeNote,
		arg.CreatedBy,
	)
	var i QrVersion
	err := row.Scan(
		&i.ID,
		&i.QrCodeID,
		&i.VersionNo,
		&i.DestinationKind,
		&i.DestinationUrl,
		&i.HostedPage,
		&i.Rules,
		&i.Utm,
		&i.EffectiveAt,
		&i.SafetyStatus,
		&i.RestoredFrom,
		&i.ChangeNote,
		&i.CreatedBy,
		&i.CreatedByKey,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestQRVersion = `-- name: GetLatestQRVersion :one
SELECT id, qr_code_id, version_no, destination_kind, destination_url, hosted_page, rules, utm, effective_at, safety_status, restored_from, change_note, created_by, created_by_key, created_at FROM qr_versions
WHERE qr_code_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetLatestQRVersion(ctx context.Context, qrCodeID uuid.UUID) (QrVersion, error) {
	row := q.db.QueryRow(ctx, getLatestQRVersion, qrCodeID)
	var i QrVersion
	err := row.Scan(
		&i.ID,
		&i.QrCodeID,
		&i.VersionNo,
		&i.DestinationKind,
		&i.DestinationUrl,
		&i.HostedPage,
		&i.Rules,
		&i.Utm,
		&i.EffectiveAt,
		&i.SafetyStatus,
		&i.RestoredFrom,
		&i.ChangeNote,
		&i.CreatedBy,
		&i.CreatedByKey,
		&i.CreatedAt,
	)
	return i, err
}

const getQRCode = `-- name: GetQRCode :one
SELECT id, workspace_id, created_by, mode, content_type, name, domain_id, short_code, legacy_short_code, gs1_gtin, static_payload, static_content, current_version_id, design, design_hash, template_id, folder_id, campaign_id, status, is_read_only, starts_at, expires_at, scan_limit, password_hash, fallback_url, safety_status, total_scans, unique_scans, last_scanned_at, created_at, updated_at, archived_at, deleted_at FROM qr_codes
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetQRCodeParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetQRCode(ctx context.Context, arg GetQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQRCode, arg.ID, arg.WorkspaceID)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Mode,
		&i.ContentType,
		&i.Name,
		&i.DomainID,
		&i.ShortCode,
		&i.LegacyShortCode,
		&i.Gs1Gtin,
		&i.StaticPayload,
		&i.StaticContent,
		&i.CurrentVersionID,
		&i.Design,
		&i.DesignHash,
		&i.TemplateID,
		&i.FolderID,
		&i.CampaignID,
		&i.Status,
		&i.IsReadOnly,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ScanLimit,
		&i.PasswordHash,
		&i.FallbackUrl,
		&i.SafetyStatus,
		&i.TotalScans,
		&i.UniqueScans,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getQRCodeByDomainAndCode = `-- name: GetQRCodeByDomainAndCode :one
SELECT id, workspace_id, created_by, mode, content_type, name, domain_id, short_code, legacy_short_code, gs1_gtin, static_payload, static_content, current_version_id, design, design_hash, template_id, folder_id, campaign_id, status, is_read_only, starts_at, expires_at, scan_limit, password_hash, fallback_url, safety_status, total_scans, unique_scans, last_scanned_at, created_at, updated_at, archived_at, deleted_at FROM qr_codes
WHERE domain_id = $1 AND short_code = $2 AND deleted_at IS NULL
`

type GetQRCodeByDomainAndCodeParams struct {
	DomainID  pgtype.UUID `json:"domain_id"`
	ShortCode *string     `json:"short_code"`
}

func (q *Queries) GetQRCodeByDomainAndCode(ctx context.Context, arg GetQRCodeByDomainAndCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQRCodeByDomainAndCode, arg.DomainID, arg.ShortCode)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Mode,
		&i.ContentType,
		&i.Name,
		&i.DomainID,
		&i.ShortCode,
		&i.LegacyShortCode,
		&i.Gs1Gtin,
		&i.StaticPayload,
		&i.StaticContent,
		&i.CurrentVersionID,
		&i.Design,
		&i.DesignHash,
		&i.TemplateID,
		&i.FolderID,
		&i.CampaignID,
		&i.Status,
		&i.IsReadOnly,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ScanLimit,
		&i.PasswordHash,
		&i.FallbackUrl,
		&i.SafetyStatus,
		&i.TotalScans,
		&i.UniqueScans,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResolvedLink = `-- name: GetResolvedLink :one
SELECT q.id AS qr_code_id,
       q.workspace_id,
       q.status AS qr_status,
       q.safety_status,
       q.starts_at,
       q.expires_at,
       q.scan_limit,
       q.total_scans,
       q.password_hash,
       q.fallback_url,
       w.timezone AS workspace_timezone,
       v.id AS version_id,
       v.version_no,
       v.destination_kind,
       v.destination_url,
       v.rules,
       v.utm,
       v.hosted_page,
       (
         SELECT min(v2.effective_at)
         FROM qr_versions v2
         WHERE v2.qr_code_id = q.id AND v2.effective_at > now()
       ) AS next_change_at
FROM qr_codes q
JOIN workspaces w ON w.id = q.workspace_id
LEFT JOIN LATERAL (
    SELECT id, qr_code_id, version_no, destination_kind, destination_url, hosted_page, rules, utm, effective_at, safety_status, restored_from, change_note, created_by, created_by_key, created_at FROM qr_versions v1
    WHERE v1.qr_code_id = q.id AND v1.effective_at <= now()
    ORDER BY v1.effective_at DESC, v1.version_no DESC
    LIMIT 1
) v ON true
WHERE q.domain_id = $1 AND q.short_code = $2 AND q.deleted_at IS NULL
`

type GetResolvedLinkParams struct {
	DomainID  pgtype.UUID `json:"domain_id"`
	ShortCode *string     `json:"short_code"`
}

type GetResolvedLinkRow struct {
	QrCodeID          uuid.UUID          `json:"qr_code_id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	QrStatus          string             `json:"qr_status"`
	SafetyStatus      string             `json:"safety_status"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ScanLimit         *int64             `json:"scan_limit"`
	TotalScans        int64              `json:"total_scans"`
	PasswordHash      *string            `json:"password_hash"`
	FallbackUrl       *string            `json:"fallback_url"`
	WorkspaceTimezone string             `json:"workspace_timezone"`
	VersionID         uuid.UUID          `json:"version_id"`
	VersionNo         int32              `json:"version_no"`
	DestinationKind   string             `json:"destination_kind"`
	DestinationUrl    *string            `json:"destination_url"`
	Rules             json.RawMessage    `json:"rules"`
	Utm               json.RawMessage    `json:"utm"`
	HostedPage        []byte             `json:"hosted_page"`
	NextChangeAt      interface{}        `json:"next_change_at"`
}

func (q *Queries) GetResolvedLink(ctx context.Context, arg GetResolvedLinkParams) (GetResolvedLinkRow, error) {
	row := q.db.QueryRow(ctx, getResolvedLink, arg.DomainID, arg.ShortCode)
	var i GetResolvedLinkRow
	err := row.Scan(
		&i.QrCodeID,
		&i.WorkspaceID,
		&i.QrStatus,
		&i.SafetyStatus,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ScanLimit,
		&i.TotalScans,
		&i.PasswordHash,
		&i.FallbackUrl,
		&i.WorkspaceTimezone,
		&i.VersionID,
		&i.VersionNo,
		&i.DestinationKind,
		&i.DestinationUrl,
		&i.Rules,
		&i.Utm,
		&i.HostedPage,
		&i.NextChangeAt,
	)
	return i, err
}

const listQRCodes = `-- name: ListQRCodes :many
SELECT q.id, q.workspace_id, q.created_by, q.mode, q.content_type, q.name, q.domain_id, q.short_code, q.legacy_short_code, q.gs1_gtin, q.static_payload, q.static_content, q.current_version_id, q.design, q.design_hash, q.template_id, q.folder_id, q.campaign_id, q.status, q.is_read_only, q.starts_at, q.expires_at, q.scan_limit, q.password_hash, q.fallback_url, q.safety_status, q.total_scans, q.unique_scans, q.last_scanned_at, q.created_at, q.updated_at, q.archived_at, q.deleted_at, v.destination_url, v.destination_kind
FROM qr_codes q
LEFT JOIN qr_versions v ON v.id = q.current_version_id
WHERE q.workspace_id = $1
  AND q.deleted_at IS NULL
  AND ($2::text IS NULL OR q.name ILIKE '%' || $2 || '%' OR q.short_code ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR q.status = $3)
ORDER BY q.created_at DESC
LIMIT $4
`

type ListQRCodesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Search      *string   `json:"search"`
	Status      *string   `json:"status"`
	RowLimit    int32     `json:"row_limit"`
}

type ListQRCodesRow struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Mode             string             `json:"mode"`
	ContentType      string             `json:"content_type"`
	Name             string             `json:"name"`
	DomainID         pgtype.UUID        `json:"domain_id"`
	ShortCode        *string            `json:"short_code"`
	LegacyShortCode  *string            `json:"legacy_short_code"`
	Gs1Gtin          *string            `json:"gs1_gtin"`
	StaticPayload    *string            `json:"static_payload"`
	StaticContent    []byte             `json:"static_content"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	Design           json.RawMessage    `json:"design"`
	DesignHash       []byte             `json:"design_hash"`
	TemplateID       pgtype.UUID        `json:"template_id"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	Status           string             `json:"status"`
	IsReadOnly       bool               `json:"is_read_only"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ScanLimit        *int64             `json:"scan_limit"`
	PasswordHash     *string            `json:"password_hash"`
	FallbackUrl      *string            `json:"fallback_url"`
	SafetyStatus     string             `json:"safety_status"`
	TotalScans       int64              `json:"total_scans"`
	UniqueScans      int64              `json:"unique_scans"`
	LastScannedAt    pgtype.Timestamptz `json:"last_scanned_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DestinationUrl   *string            `json:"destination_url"`
	DestinationKind  *string            `json:"destination_kind"`
}

func (q *Queries) ListQRCodes(ctx context.Context, arg ListQRCodesParams) ([]ListQRCodesRow, error) {
	rows, err := q.db.Query(ctx, listQRCodes,
		arg.WorkspaceID,
		arg.Search,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQRCodesRow{}
	for rows.Next() {
		var i ListQRCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Mode,
			&i.ContentType,
			&i.Name,
			&i.DomainID,
			&i.ShortCode,
			&i.LegacyShortCode,
			&i.Gs1Gtin,
			&i.StaticPayload,
			&i.StaticContent,
			&i.CurrentVersionID,
			&i.Design,
			&i.DesignHash,
			&i.TemplateID,
			&i.FolderID,
			&i.CampaignID,
			&i.Status,
			&i.IsReadOnly,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ScanLimit,
			&i.PasswordHash,
			&i.FallbackUrl,
			&i.SafetyStatus,
			&i.TotalScans,
			&i.UniqueScans,
			&i.LastScannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.DestinationUrl,
			&i.DestinationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQRVersions = `-- name: ListQRVersions :many
SELECT id, qr_code_id, version_no, destination_kind, destination_url, hosted_page, rules, utm, effective_at, safety_status, restored_from, change_note, created_by, created_by_key, created_at FROM qr_versions
WHERE qr_code_id = $1
ORDER BY version_no DESC
`

func (q *Queries) ListQRVersions(ctx context.Context, qrCodeID uuid.UUID) ([]QrVersion, error) {
	rows, err := q.db.Query(ctx, listQRVersions, qrCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QrVersion{}
	for rows.Next() {
		var i QrVersion
		if err := rows.Scan(
			&i.ID,
			&i.QrCodeID,
			&i.VersionNo,
			&i.DestinationKind,
			&i.DestinationUrl,
			&i.HostedPage,
			&i.Rules,
			&i.Utm,
			&i.EffectiveAt,
			&i.SafetyStatus,
			&i.RestoredFrom,
			&i.ChangeNote,
			&i.CreatedBy,
			&i.CreatedByKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteQRCode = `-- name: SoftDeleteQRCode :exec
UPDATE qr_codes
SET deleted_at = now()
WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteQRCodeParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SoftDeleteQRCode(ctx context.Context, arg SoftDeleteQRCodeParams) error {
	_, err := q.db.Exec(ctx, softDeleteQRCode, arg.ID, arg.WorkspaceID)
	return err
}

const updateQRCode = `-- name: UpdateQRCode :one
UPDATE qr_codes
SET name = COALESCE($1, name),
    design = COALESCE($2, design),
    design_hash = COALESCE($3, design_hash),
    status = COALESCE($4, status),
    folder_id = COALESCE($5, folder_id),
    current_version_id = COALESCE($6, current_version_id),
    updated_at = now()
WHERE id = $7 AND workspace_id = $8 AND deleted_at IS NULL
RETURNING id, workspace_id, created_by, mode, content_type, name, domain_id, short_code, legacy_short_code, gs1_gtin, static_payload, static_content, current_version_id, design, design_hash, template_id, folder_id, campaign_id, status, is_read_only, starts_at, expires_at, scan_limit, password_hash, fallback_url, safety_status, total_scans, unique_scans, last_scanned_at, created_at, updated_at, archived_at, deleted_at
`

type UpdateQRCodeParams struct {
	Name             *string     `json:"name"`
	Design           []byte      `json:"design"`
	DesignHash       []byte      `json:"design_hash"`
	Status           *string     `json:"status"`
	FolderID         pgtype.UUID `json:"folder_id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
	ID               uuid.UUID   `json:"id"`
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, updateQRCode,
		arg.Name,
		arg.Design,
		arg.DesignHash,
		arg.Status,
		arg.FolderID,
		arg.CurrentVersionID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Mode,
		&i.ContentType,
		&i.Name,
		&i.DomainID,
		&i.ShortCode,
		&i.LegacyShortCode,
		&i.Gs1Gtin,
		&i.StaticPayload,
		&i.StaticContent,
		&i.CurrentVersionID,
		&i.Design,
		&i.DesignHash,
		&i.TemplateID,
		&i.FolderID,
		&i.CampaignID,
		&i.Status,
		&i.IsReadOnly,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ScanLimit,
		&i.PasswordHash,
		&i.FallbackUrl,
		&i.SafetyStatus,
		&i.TotalScans,
		&i.UniqueScans,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}
