// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :execrows
UPDATE email_tokens SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumeEmailToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (id, user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type CreateEmailTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (id, user_id, provider, provider_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthAccountParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, created_at, last_used_at, expires_at, revoked_at, replaced_by
`

type CreateSessionParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	FamilyID         uuid.UUID `json:"family_id"`
	RefreshTokenHash []byte    `json:"refresh_token_hash"`
	UserAgent        *string   `json:"user_agent"`
	IpPrefix         *string   `json:"ip_prefix"`
	ExpiresAt        time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpPrefix,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, name, avatar_url, locale, timezone, is_staff)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, email_verified_at, password_hash, name, avatar_url, locale, timezone, is_staff, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash *string   `json:"password_hash"`
	Name         string    `json:"name"`
	AvatarUrl    *string   `json:"avatar_url"`
	Locale       string    `json:"locale"`
	Timezone     string    `json:"timezone"`
	IsStaff      bool      `json:"is_staff"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
		arg.IsStaff,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.IsStaff,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT id, user_id, purpose, token_hash, expires_at, used_at, created_at FROM email_tokens
WHERE token_hash = $1 AND expires_at > now() AND used_at IS NULL
`

func (q *Queries) GetEmailToken(ctx context.Context, tokenHash []byte) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailToken, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, created_at, last_used_at, expires_at, revoked_at, replaced_by FROM sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, created_at, last_used_at, expires_at, revoked_at, replaced_by FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, name, avatar_url, locale, timezone, is_staff, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.IsStaff,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, name, avatar_url, locale, timezone, is_staff, last_login_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.IsStaff,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getValidEmailToken = `-- name: GetValidEmailToken :one
SELECT id, user_id, purpose, token_hash, expires_at, used_at, created_at FROM email_tokens
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
`

type GetValidEmailTokenParams struct {
	TokenHash []byte `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getValidEmailToken, arg.TokenHash, arg.Purpose)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateEmailTokens = `-- name: InvalidateEmailTokens :exec
UPDATE email_tokens SET used_at = now() WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidateEmailTokensParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateEmailTokens, arg.UserID, arg.Purpose)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, created_at, last_used_at, expires_at, revoked_at, replaced_by FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND replaced_by IS NULL AND expires_at > now()
ORDER BY last_used_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ReplacedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, familyID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET replaced_by = $2,
    last_used_at = now()
WHERE id = $1
RETURNING id, user_id, family_id, refresh_token_hash, user_agent, ip_prefix, created_at, last_used_at, expires_at, revoked_at, replaced_by
`

type RotateSessionParams struct {
	ID         uuid.UUID   `json:"id"`
	ReplacedBy pgtype.UUID `json:"replaced_by"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.ReplacedBy)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const setLastLogin = `-- name: SetLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) SetLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setLastLogin, id)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($2, name),
    avatar_url = COALESCE($3, avatar_url),
    locale = COALESCE($4, locale),
    timezone = COALESCE($5, timezone),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, email_verified_at, password_hash, name, avatar_url, locale, timezone, is_staff, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	Locale    string    `json:"locale"`
	Timezone  string    `json:"timezone"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.AvatarUrl,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.IsStaff,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
