// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE invites
SET accepted_at = now()
WHERE id = $1
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvite, id)
	return err
}

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateInviteParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	TokenHash   []byte    `json:"token_hash"`
	InvitedBy   uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug, owner_id, plan_id, timezone, brand, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, slug, owner_id, plan_id, timezone, default_domain_id, brand, settings, created_at, updated_at, deleted_at
`

type CreateWorkspaceParams struct {
	ID       uuid.UUID       `json:"id"`
	Name     string          `json:"name"`
	Slug     string          `json:"slug"`
	OwnerID  uuid.UUID       `json:"owner_id"`
	PlanID   string          `json:"plan_id"`
	Timezone string          `json:"timezone"`
	Brand    json.RawMessage `json:"brand"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OwnerID,
		arg.PlanID,
		arg.Timezone,
		arg.Brand,
		arg.Settings,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.PlanID,
		&i.Timezone,
		&i.DefaultDomainID,
		&i.Brand,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM invites
WHERE token_hash = $1 AND expires_at > now() AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) GetInviteByHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, owner_id, plan_id, timezone, default_domain_id, brand, settings, created_at, updated_at, deleted_at FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.PlanID,
		&i.Timezone,
		&i.DefaultDomainID,
		&i.Brand,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, owner_id, plan_id, timezone, default_domain_id, brand, settings, created_at, updated_at, deleted_at FROM workspaces
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.PlanID,
		&i.Timezone,
		&i.DefaultDomainID,
		&i.Brand,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, created_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.user_id, m.role, m.created_at, u.email, u.name, u.avatar_url
FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.created_at
`

type ListWorkspaceMembersRow struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	AvatarUrl   *string   `json:"avatar_url"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.slug, w.owner_id, w.plan_id, w.timezone, w.default_domain_id, w.brand, w.settings, w.created_at, w.updated_at, w.deleted_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1 AND w.deleted_at IS NULL
ORDER BY w.name
`

type ListWorkspacesForUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	OwnerID         uuid.UUID          `json:"owner_id"`
	PlanID          string             `json:"plan_id"`
	Timezone        string             `json:"timezone"`
	DefaultDomainID pgtype.UUID        `json:"default_domain_id"`
	Brand           json.RawMessage    `json:"brand"`
	Settings        json.RawMessage    `json:"settings"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Role            string             `json:"role"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.PlanID,
			&i.Timezone,
			&i.DefaultDomainID,
			&i.Brand,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites
SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2
`

type RevokeInviteParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.WorkspaceID)
	return err
}

const transferWorkspaceOwnership = `-- name: TransferWorkspaceOwnership :exec
UPDATE workspaces
SET owner_id = $2, updated_at = now()
WHERE id = $1
`

type TransferWorkspaceOwnershipParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) TransferWorkspaceOwnership(ctx context.Context, arg TransferWorkspaceOwnershipParams) error {
	_, err := q.db.Exec(ctx, transferWorkspaceOwnership, arg.ID, arg.OwnerID)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}
