version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DEBUG: "True"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8084
    ports:
      - "8084:8084"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8084/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3000:3000"
