# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PixelConsentDaily",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "qr_code_id",
                        "day",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qr_code_id", models.UUIDField()),
                ("day", models.DateField()),
                ("shown", models.IntegerField(default=0)),
                ("accepted", models.IntegerField(default=0)),
                ("declined", models.IntegerField(default=0)),
                ("auto_fired", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "pixel_consent_daily",
            },
        ),
        migrations.CreateModel(
            name="Pixel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[
                            ("meta", "Meta"),
                            ("google", "Google"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                        ]
                    ),
                ),
                ("external_id", models.TextField()),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixels",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "pixels",
            },
        ),
        migrations.CreateModel(
            name="QRCodePixel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "qr_code_id",
                        "pixel_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pixel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_links",
                        to="pixels.pixel",
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixel_links",
                        to="qr.qrcode",
                    ),
                ),
            ],
            options={
                "db_table": "qr_code_pixels",
            },
        ),
        migrations.AddConstraint(
            model_name="pixel",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["meta", "google", "linkedin", "tiktok"])),
                name="pixels_provider_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="pixel",
            constraint=models.CheckConstraint(
                condition=models.Q(("external_id__regex", "^[A-Za-z0-9_-]{3,40}$")),
                name="pixels_external_id_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="pixel",
            constraint=models.UniqueConstraint(
                fields=("workspace", "provider", "external_id"),
                name="pixels_workspace_id_provider_external_id_key",
            ),
        ),
    ]
