# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.alerts.models
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "workspaces",
            "0002_workspacepolicy_remove_invite_invites_role_check_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("scan_spike", "Scan Spike"),
                            ("scan_drop", "Scan Drop"),
                            ("scan_threshold", "Scan Threshold"),
                            ("no_scans", "No Scans"),
                            ("destination_down", "Destination Down"),
                            ("serial_anomaly", "Serial Anomaly"),
                            ("security_event", "Security Event"),
                            ("approval_pending", "Approval Pending"),
                        ]
                    ),
                ),
                (
                    "target_type",
                    models.TextField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("qr_code", "QR Code"),
                            ("campaign", "Campaign"),
                            ("serial_batch", "Serial Batch"),
                        ]
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("params", models.JSONField(default=dict)),
                (
                    "channels",
                    models.JSONField(default=apps.alerts.models.default_alert_channels),
                ),
                ("cooldown_minutes", models.IntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "alert_rules",
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fired_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "alert_events",
            },
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "scan_spike",
                            "scan_drop",
                            "scan_threshold",
                            "no_scans",
                            "destination_down",
                            "serial_anomaly",
                            "security_event",
                            "approval_pending",
                        ],
                    )
                ),
                name="alert_rules_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        ["workspace", "qr_code", "campaign", "serial_batch"],
                    )
                ),
                name="alert_rules_target_type_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("cooldown_minutes__gte", 5), ("cooldown_minutes__lte", 10080)),
                name="alert_rules_cooldown_minutes_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_type", "workspace"), ("target_id__isnull", True)),
                    models.Q(
                        models.Q(("target_type", "workspace"), _negated=True),
                        ("target_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="alert_target",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["rule", "-fired_at"], name="alert_events_rule_idx"),
        ),
    ]
