# Generated by Django 6.1.1 on 2026-10-03 15:37

import datetime

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        choices=[("read", "Read"), ("read_write", "Read/Write")],
                        default="read",
                    ),
                ),
                ("reason", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_support_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_grants",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "db_table": "support_access_grants",
            },
        ),
        migrations.CreateModel(
            name="SupportSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="staff.supportaccessgrant",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_sessions",
                        to="orgs.organization",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_sessions",
            },
        ),
        migrations.AddIndex(
            model_name="supportaccessgrant",
            index=models.Index(fields=["org", "-created_at"], name="support_access_grants_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="supportaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope__in", ["read", "read_write"])),
                name="support_access_grants_scope_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="supportaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "expires_at__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("created_at"),
                            "+",
                            models.Value(datetime.timedelta(days=7)),
                        ),
                    )
                ),
                name="support_grant_max_7d",
            ),
        ),
        migrations.AddIndex(
            model_name="supportsession",
            index=models.Index(fields=["org", "-started_at"], name="support_sessions_org_idx"),
        ),
    ]
