# Generated by Django 6.1.1 on 2026-10-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportaccessgrant",
            name="granted_by",
            field=models.ForeignKey(
                db_column="granted_by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="granted_support_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
