# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "workspace_id",
                        "key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField()),
                ("key", models.TextField()),
                ("method", models.TextField()),
                ("path", models.TextField()),
                ("request_hash", models.BinaryField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "idempotency_keys",
                "indexes": [models.Index(fields=["expires_at"], name="idempotency_expiry_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key__regex", "^.{8,128}$")),
                        name="idempotency_keys_key_check",
                    )
                ],
            },
        ),
    ]
