# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbuseReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", apps.core.fields.CIText()),
                ("short_code", models.TextField()),
                ("reason", models.TextField()),
                ("details", models.TextField(blank=True, null=True)),
                ("reporter_email", apps.core.fields.CIText(blank=True, null=True)),
                ("reporter_ip_prefix", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="open")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="qr_code_id",
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        related_name="abuse_reports",
                        to="qr.qrcode",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="resolved_by",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="resolved_abuse_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "abuse_reports",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "open")),
                        fields=["created_at"],
                        name="abuse_reports_open_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason__in",
                                [
                                    "phishing",
                                    "malware",
                                    "scam",
                                    "spam",
                                    "illegal",
                                    "other",
                                ],
                            )
                        ),
                        name="abuse_reports_reason_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "actioned", "dismissed"])),
                        name="abuse_reports_status_check",
                    ),
                ],
            },
        ),
    ]
