# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                ("actor_type", models.TextField()),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("action", models.TextField()),
                ("target_type", models.TextField()),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("changes", models.JSONField(default=dict)),
                ("ip_prefix", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "-created_at"],
                        name="audit_logs_ws_time_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actor_type__in", ["user", "api_key", "system", "staff"])
                        ),
                        name="audit_logs_actor_type_check",
                    )
                ],
            },
        ),
    ]
