# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        ("orgs", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditAnchor",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org_id",
                        "day",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField()),
                ("day", models.DateField()),
                ("last_seq", models.BigIntegerField()),
                ("head_hash", models.BinaryField()),
                ("object_key", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_anchors",
            },
        ),
        migrations.CreateModel(
            name="AuditStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("splunk_hec", "Splunk HEC"),
                            ("datadog", "Datadog"),
                            ("s3", "S3"),
                        ]
                    ),
                ),
                ("label", models.TextField(default="")),
                ("config", models.JSONField()),
                ("secret_ct", models.BinaryField(blank=True, null=True)),
                ("cursor_seq", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                        ],
                        default="active",
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("failing_since", models.DateTimeField(blank=True, null=True)),
                ("last_delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_streams",
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="hash",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="org_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="prev_hash",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="sealed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="seq",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                condition=models.Q(("hash__isnull", True)),
                fields=["org_id", "id"],
                name="audit_logs_unsealed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                condition=models.Q(("org_id__isnull", False)),
                fields=["org_id", "-created_at"],
                name="audit_logs_org_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seq__isnull", False)),
                fields=("org_id", "seq"),
                name="audit_logs_org_seq_uniq",
            ),
        ),
        migrations.AddField(
            model_name="auditstream",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditstream",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_streams",
                to="orgs.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="auditstream",
            index=models.Index(fields=["org"], name="audit_streams_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="auditstream",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["webhook", "splunk_hec", "datadog", "s3"])),
                name="audit_streams_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditstream",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "paused", "error"])),
                name="audit_streams_status_check",
            ),
        ),
    ]
