# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("developer", "0002_initial"),
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("create", "Create"),
                            ("destination", "Destination"),
                            ("rules", "Rules"),
                            ("bulk_update", "Bulk Update"),
                        ]
                    ),
                ),
                (
                    "reasons",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField()),
                ),
                ("required_approvals", models.IntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="developer.job",
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="qr.qrcode",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "approval_requests",
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "request_id",
                        "approver_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.TextField(choices=[("approve", "Approve"), ("reject", "Reject")]),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="approvals.approvalrequest",
                    ),
                ),
            ],
            options={
                "db_table": "approval_decisions",
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["workspace", "created_at"],
                name="approval_requests_ws_pend_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["expires_at"],
                name="approval_req_pend_exp_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requested_by", "-created_at"],
                name="approval_req_requester_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["create", "destination", "rules", "bulk_update"])),
                name="approval_requests_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_approvals__gte", 1), ("required_approvals__lte", 3)),
                name="approval_requests_required_approvals_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "approved", "rejected", "cancelled", "expired"],
                    )
                ),
                name="approval_requests_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("job__isnull", False),
                        ("kind", "bulk_update"),
                        ("qr_code__isnull", True),
                    ),
                    models.Q(
                        models.Q(("kind", "bulk_update"), _negated=True),
                        ("job__isnull", True),
                        ("qr_code__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="approval_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvaldecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ["approve", "reject"])),
                name="approval_decisions_decision_check",
            ),
        ),
    ]
