# Generated by Django 6.1.1 on 2026-10-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0002_approval_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                db_column="requested_by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
