# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="workspace",
            field=models.OneToOneField(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="subscription",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["stripe", "razorpay"])),
                name="subscriptions_provider_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan_id__in", ["pro", "business", "enterprise"])),
                name="subscriptions_plan_id_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("billing_interval__in", ["month", "year"])),
                name="subscriptions_billing_interval_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "trialing",
                            "active",
                            "past_due",
                            "paused",
                            "canceled",
                            "incomplete",
                        ],
                    )
                ),
                name="subscriptions_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats__gt", 0)), name="subscriptions_seats_check"
            ),
        ),
    ]
