# Generated by Django 6.1.1 on 2026-10-03 15:37

from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
        ("orgs", "__first__"),
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "billing_interval",
                    models.TextField(
                        choices=[
                            ("month", "Month"),
                            ("quarter", "Quarter"),
                            ("year", "Year"),
                        ]
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.FixedCharField(
                        choices=[
                            ("INR", "INR"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("seats", models.IntegerField()),
                ("limits_override", models.JSONField(default=dict)),
                (
                    "sla_uptime",
                    models.DecimalField(decimal_places=3, default=Decimal("99.950"), max_digits=5),
                ),
                ("po_number", models.TextField(blank=True, null=True)),
                ("payment_terms_days", models.IntegerField(default=30)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "contracts",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.TextField(unique=True)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("currency", apps.core.fields.FixedCharField(max_length=3)),
                (
                    "tax_mode",
                    models.TextField(
                        choices=[
                            ("cgst_sgst", "CGST + SGST"),
                            ("igst", "IGST"),
                            ("export_lut", "Export under LUT"),
                            ("reverse_charge", "Reverse Charge"),
                            ("none", "None"),
                        ]
                    ),
                ),
                ("place_of_supply", models.TextField()),
                ("seller", models.JSONField()),
                ("buyer", models.JSONField()),
                ("lines", models.JSONField()),
                ("subtotal_minor", models.BigIntegerField()),
                ("cgst_minor", models.BigIntegerField(default=0)),
                ("sgst_minor", models.BigIntegerField(default=0)),
                ("igst_minor", models.BigIntegerField(default=0)),
                ("total_minor", models.BigIntegerField()),
                ("endorsement", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="issued",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("payment_link_id", models.TextField(blank=True, null=True)),
                ("payment_link_url", models.TextField(blank=True, null=True)),
                ("reminders_sent", models.IntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True, null=True)),
                ("paid_reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                ("fy", models.TextField(primary_key=True, serialize=False)),
                ("last_seq", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "invoice_sequences",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_column="workspace_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["trialing", "active", "past_due", "paused"])),
                fields=("org",),
                name="subscriptions_org_uniq",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.contract",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="qr.file",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicesequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("fy__regex", "^[0-9]{4}-[0-9]{2}$")),
                name="invoice_sequences_fy_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gt", models.F("starts_on"))),
                name="contracts_ends_on_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("billing_interval__in", ["month", "quarter", "year"])),
                name="contracts_billing_interval_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["INR", "USD", "EUR", "GBP"])),
                name="contracts_currency_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_minor__gte", 0)),
                name="contracts_amount_minor_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats__gt", 0)), name="contracts_seats_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "expired", "terminated"])),
                name="contracts_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("org",),
                name="contracts_one_active_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["org", "-issue_date"], name="invoices_org_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                condition=models.Q(("status", "issued")),
                fields=["due_date"],
                name="invoices_unpaid_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tax_mode__in",
                        ["cgst_sgst", "igst", "export_lut", "reverse_charge", "none"],
                    )
                ),
                name="invoices_tax_mode_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["issued", "paid", "void"])),
                name="invoices_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_minor",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("subtotal_minor"),
                                    "+",
                                    models.F("cgst_minor"),
                                ),
                                "+",
                                models.F("sgst_minor"),
                            ),
                            "+",
                            models.F("igst_minor"),
                        ),
                    )
                ),
                name="invoice_totals",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tax_mode", "export_lut"), _negated=True),
                    models.Q(
                        ("cgst_minor", 0),
                        ("sgst_minor", 0),
                        ("igst_minor", 0),
                        ("endorsement__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="invoice_export_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("contract__isnull", False),
                    ("period_start__isnull", False),
                    models.Q(("status", "void"), _negated=True),
                ),
                fields=("contract", "period_start"),
                name="invoices_contract_period_uniq",
            ),
        ),
    ]
