# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        ("qr", "0003_remove_qrcode_qr_codes_content_type_check_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgBranding",
            fields=[
                (
                    "org",
                    models.OneToOneField(
                        db_column="org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="branding",
                        serialize=False,
                        to="orgs.organization",
                    ),
                ),
                (
                    "app_hostname",
                    apps.core.fields.CIText(blank=True, null=True, unique=True),
                ),
                (
                    "app_hostname_status",
                    models.TextField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                    ),
                ),
                ("provider_hostname_id", models.TextField(blank=True, null=True)),
                (
                    "email_domain",
                    apps.core.fields.CIText(blank=True, null=True, unique=True),
                ),
                (
                    "email_domain_status",
                    models.TextField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                    ),
                ),
                ("email_provider_id", models.TextField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                ("primary_color", models.TextField(blank=True, null=True)),
                ("support_url", models.TextField(blank=True, null=True)),
                ("hide_platform_brand", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "favicon_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="qr.file",
                    ),
                ),
                (
                    "logo_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="qr.file",
                    ),
                ),
            ],
            options={
                "db_table": "org_branding",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "app_hostname_status__in",
                                ["none", "pending", "active", "failed"],
                            )
                        ),
                        name="org_branding_app_hostname_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "email_domain_status__in",
                                ["none", "pending", "active", "failed"],
                            )
                        ),
                        name="org_branding_email_domain_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("primary_color__isnull", True),
                            ("primary_color__regex", "^#[0-9A-Fa-f]{6}$"),
                            _connector="OR",
                        ),
                        name="org_branding_primary_color_check",
                    ),
                ],
            },
        ),
    ]
