# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.utils.timezone
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyEmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("email", apps.core.fields.CIText()),
                ("email_type", models.TextField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "legacy_email_log",
            },
        ),
        migrations.CreateModel(
            name="LegacyIdMap",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "entity",
                        "v1_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity", models.TextField()),
                ("v1_id", models.UUIDField()),
                ("v3_id", models.TextField()),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("checksum", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "legacy_id_map",
            },
        ),
        migrations.CreateModel(
            name="LegacyImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(default="running")),
                ("stats", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "legacy_import_runs",
            },
        ),
    ]
