// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (workspace_id, key, method, path, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING workspace_id, key, method, path, request_hash, status_code, response_body, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Key         string    `json:"key"`
	Method      string    `json:"method"`
	Path        string    `json:"path"`
	RequestHash []byte    `json:"request_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.WorkspaceID,
		arg.Key,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.WorkspaceID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE workspace_id = $1 AND key = $2
`

type DeleteIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Key         string    `json:"key"`
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.WorkspaceID, arg.Key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT workspace_id, key, method, path, request_hash, status_code, response_body, created_at, expires_at FROM idempotency_keys
WHERE workspace_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Key         string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.WorkspaceID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.WorkspaceID,
		&i.Key,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :exec
UPDATE idempotency_keys
SET status_code = $3,
    response_body = $4
WHERE workspace_id = $1 AND key = $2
`

type SetIdempotencyResponseParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Key          string    `json:"key"`
	StatusCode   *int32    `json:"status_code"`
	ResponseBody []byte    `json:"response_body"`
}

func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyResponse,
		arg.WorkspaceID,
		arg.Key,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}
