// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organize.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addQRTags = `-- name: AddQRTags :exec
INSERT INTO qr_code_tags (qr_code_id, tag_id)
SELECT $1, t.id FROM tags t
WHERE t.workspace_id = $2 AND t.id = ANY($3::uuid[])
ON CONFLICT DO NOTHING
`

type AddQRTagsParams struct {
	QrCodeID    uuid.UUID   `json:"qr_code_id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	TagIds      []uuid.UUID `json:"tag_ids"`
}

// Only tags belonging to the code's workspace are attached.
func (q *Queries) AddQRTags(ctx context.Context, arg AddQRTagsParams) error {
	_, err := q.db.Exec(ctx, addQRTags, arg.QrCodeID, arg.WorkspaceID, arg.TagIds)
	return err
}

const clearDefaultTemplate = `-- name: ClearDefaultTemplate :exec
UPDATE templates SET is_default = false WHERE workspace_id = $1 AND is_default
`

func (q *Queries) ClearDefaultTemplate(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultTemplate, workspaceID)
	return err
}

const clearQRTags = `-- name: ClearQRTags :exec
DELETE FROM qr_code_tags WHERE qr_code_id = $1
`

func (q *Queries) ClearQRTags(ctx context.Context, qrCodeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearQRTags, qrCodeID)
	return err
}

const countTemplates = `-- name: CountTemplates :one
SELECT count(*)::int FROM templates WHERE workspace_id = $1
`

func (q *Queries) CountTemplates(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTemplates, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, workspace_id, name, status, starts_at, ends_at, goal_scans, utm, created_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, workspace_id, name, status, starts_at, ends_at, goal_scans, utm, created_by, created_at, updated_at
`

type CreateCampaignParams struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	GoalScans   *int64             `json:"goal_scans"`
	Utm         json.RawMessage    `json:"utm"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.GoalScans,
		arg.Utm,
		arg.CreatedBy,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.GoalScans,
		&i.Utm,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (id, workspace_id, parent_id, name, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, parent_id, name, position, created_at, updated_at
`

type CreateFolderParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Position,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, workspace_id, name, color) VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, name, color, created_at
`

type CreateTagParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (id, workspace_id, name, design, is_locked, is_default, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, name, design, is_locked, is_default, created_by, created_at, updated_at
`

type CreateTemplateParams struct {
	ID          uuid.UUID       `json:"id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Name        string          `json:"name"`
	Design      json.RawMessage `json:"design"`
	IsLocked    bool            `json:"is_locked"`
	IsDefault   bool            `json:"is_default"`
	CreatedBy   pgtype.UUID     `json:"created_by"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Design,
		arg.IsLocked,
		arg.IsDefault,
		arg.CreatedBy,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Design,
		&i.IsLocked,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :execrows
DELETE FROM campaigns WHERE id = $1 AND workspace_id = $2
`

type DeleteCampaignParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCampaign, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFolder = `-- name: DeleteFolder :execrows
DELETE FROM folders WHERE id = $1 AND workspace_id = $2
`

type DeleteFolderParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1 AND workspace_id = $2
`

type DeleteTagParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = $1 AND workspace_id = $2
`

type DeleteTemplateParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const folderAncestors = `-- name: FolderAncestors :many
WITH RECURSIVE chain AS (
    SELECT f.id, f.parent_id, 0 AS depth FROM folders f WHERE f.id = $1 AND f.workspace_id = $2
    UNION ALL
    SELECT p.id, p.parent_id, c.depth + 1 FROM folders p JOIN chain c ON p.id = c.parent_id WHERE c.depth < 32
)
SELECT id FROM chain ORDER BY depth
`

type FolderAncestorsParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// The folder itself and every ancestor, nearest first (used for folder-scoped permissions and cycle checks).
func (q *Queries) FolderAncestors(ctx context.Context, arg FolderAncestorsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderAncestors, arg.ID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folderDescendants = `-- name: FolderDescendants :many
WITH RECURSIVE tree AS (
    SELECT f.id, 0 AS depth FROM folders f WHERE f.id = $1 AND f.workspace_id = $2
    UNION ALL
    SELECT c.id, t.depth + 1 FROM folders c JOIN tree t ON c.parent_id = t.id WHERE t.depth < 32
)
SELECT id FROM tree
`

type FolderDescendantsParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) FolderDescendants(ctx context.Context, arg FolderDescendantsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, folderDescendants, arg.ID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, workspace_id, name, status, starts_at, ends_at, goal_scans, utm, created_by, created_at, updated_at FROM campaigns WHERE id = $1 AND workspace_id = $2
`

type GetCampaignParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.ID, arg.WorkspaceID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.GoalScans,
		&i.Utm,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultTemplate = `-- name: GetDefaultTemplate :one
SELECT id, workspace_id, name, design, is_locked, is_default, created_by, created_at, updated_at FROM templates WHERE workspace_id = $1 AND is_default
`

func (q *Queries) GetDefaultTemplate(ctx context.Context, workspaceID uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getDefaultTemplate, workspaceID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Design,
		&i.IsLocked,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolder = `-- name: GetFolder :one
SELECT id, workspace_id, parent_id, name, position, created_at, updated_at FROM folders WHERE id = $1 AND workspace_id = $2
`

type GetFolderParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, arg.ID, arg.WorkspaceID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, workspace_id, name, design, is_locked, is_default, created_by, created_at, updated_at FROM templates WHERE id = $1 AND workspace_id = $2
`

type GetTemplateParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.ID, arg.WorkspaceID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Design,
		&i.IsLocked,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT c.id, c.workspace_id, c.name, c.status, c.starts_at, c.ends_at, c.goal_scans, c.utm, c.created_by, c.created_at, c.updated_at,
       (SELECT count(*) FROM qr_codes q WHERE q.campaign_id = c.id AND q.deleted_at IS NULL)::int AS qr_count,
       (SELECT COALESCE(sum(q.total_scans), 0) FROM qr_codes q WHERE q.campaign_id = c.id AND q.deleted_at IS NULL)::bigint AS total_scans
FROM campaigns c WHERE c.workspace_id = $1
ORDER BY c.created_at DESC
`

type ListCampaignsRow struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Status      string             `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	GoalScans   *int64             `json:"goal_scans"`
	Utm         json.RawMessage    `json:"utm"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	QrCount     int32              `json:"qr_count"`
	TotalScans  int64              `json:"total_scans"`
}

func (q *Queries) ListCampaigns(ctx context.Context, workspaceID uuid.UUID) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsRow{}
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.GoalScans,
			&i.Utm,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QrCount,
			&i.TotalScans,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many

SELECT f.id, f.workspace_id, f.parent_id, f.name, f.position, f.created_at, f.updated_at, (SELECT count(*) FROM qr_codes q WHERE q.folder_id = f.id AND q.deleted_at IS NULL)::int AS qr_count
FROM folders f WHERE f.workspace_id = $1
ORDER BY f.parent_id NULLS FIRST, f.position, f.name
`

type ListFoldersRow struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	QrCount     int32       `json:"qr_count"`
}

// Folders, tags and campaigns: how a workspace organises its codes.
func (q *Queries) ListFolders(ctx context.Context, workspaceID uuid.UUID) ([]ListFoldersRow, error) {
	rows, err := q.db.Query(ctx, listFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoldersRow{}
	for rows.Next() {
		var i ListFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QrCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQRTags = `-- name: ListQRTags :many
SELECT t.id, t.workspace_id, t.name, t.color, t.created_at FROM tags t JOIN qr_code_tags x ON x.tag_id = t.id WHERE x.qr_code_id = $1 ORDER BY t.name
`

func (q *Queries) ListQRTags(ctx context.Context, qrCodeID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listQRTags, qrCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.workspace_id, t.name, t.color, t.created_at, (SELECT count(*) FROM qr_code_tags x JOIN qr_codes q ON q.id = x.qr_code_id
             WHERE x.tag_id = t.id AND q.deleted_at IS NULL)::int AS qr_count
FROM tags t WHERE t.workspace_id = $1 ORDER BY t.name
`

type ListTagsRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	QrCount     int32     `json:"qr_count"`
}

func (q *Queries) ListTags(ctx context.Context, workspaceID uuid.UUID) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.QrCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, workspace_id, name, design, is_locked, is_default, created_by, created_at, updated_at FROM templates WHERE workspace_id = $1 ORDER BY is_default DESC, name
`

func (q *Queries) ListTemplates(ctx context.Context, workspaceID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Design,
			&i.IsLocked,
			&i.IsDefault,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns SET
    name       = COALESCE($1, name),
    status     = COALESCE($2, status),
    starts_at  = CASE WHEN $3::bool THEN $4 ELSE starts_at END,
    ends_at    = CASE WHEN $5::bool THEN $6 ELSE ends_at END,
    goal_scans = CASE WHEN $7::bool THEN $8 ELSE goal_scans END,
    utm        = COALESCE($9, utm),
    updated_at = now()
WHERE id = $10 AND workspace_id = $11
RETURNING id, workspace_id, name, status, starts_at, ends_at, goal_scans, utm, created_by, created_at, updated_at
`

type UpdateCampaignParams struct {
	Name        *string            `json:"name"`
	Status      *string            `json:"status"`
	SetStartsAt bool               `json:"set_starts_at"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	SetEndsAt   bool               `json:"set_ends_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	SetGoal     bool               `json:"set_goal"`
	GoalScans   *int64             `json:"goal_scans"`
	Utm         []byte             `json:"utm"`
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.Status,
		arg.SetStartsAt,
		arg.StartsAt,
		arg.SetEndsAt,
		arg.EndsAt,
		arg.SetGoal,
		arg.GoalScans,
		arg.Utm,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.GoalScans,
		&i.Utm,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders SET
    name      = COALESCE($1, name),
    parent_id = CASE WHEN $2::bool THEN $3 ELSE parent_id END,
    position  = COALESCE($4, position),
    updated_at = now()
WHERE id = $5 AND workspace_id = $6
RETURNING id, workspace_id, parent_id, name, position, created_at, updated_at
`

type UpdateFolderParams struct {
	Name        *string     `json:"name"`
	SetParent   bool        `json:"set_parent"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Position    *int32      `json:"position"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder,
		arg.Name,
		arg.SetParent,
		arg.ParentID,
		arg.Position,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = COALESCE($1, name), color = COALESCE($2, color)
WHERE id = $3 AND workspace_id = $4 RETURNING id, workspace_id, name, color, created_at
`

type UpdateTagParams struct {
	Name        *string   `json:"name"`
	Color       *string   `json:"color"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = COALESCE($1, name),
    design = COALESCE($2, design),
    is_locked = COALESCE($3, is_locked),
    is_default = COALESCE($4, is_default),
    updated_at = now()
WHERE id = $5 AND workspace_id = $6
RETURNING id, workspace_id, name, design, is_locked, is_default, created_by, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name        *string   `json:"name"`
	Design      []byte    `json:"design"`
	IsLocked    *bool     `json:"is_locked"`
	IsDefault   *bool     `json:"is_default"`
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Design,
		arg.IsLocked,
		arg.IsDefault,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Design,
		&i.IsLocked,
		&i.IsDefault,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
