# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension, TrigramExtension
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", apps.core.fields.CIText(unique=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "password",
                    models.TextField(blank=True, db_column="password_hash", null=True),
                ),
                ("name", models.TextField(default="")),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("locale", models.TextField(default="en")),
                ("timezone", models.TextField(default="UTC")),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="last_login_at", null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="EmailToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purpose", models.TextField()),
                ("token_hash", models.BinaryField(unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_tokens",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "purpose__in",
                                ["verify_email", "reset_password", "magic_link"],
                            )
                        ),
                        name="email_tokens_purpose_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.TextField()),
                ("provider_user_id", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "oauth_accounts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="oauth_accounts_provider_provider_user_id_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["google"])),
                        name="oauth_accounts_provider_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("family_id", models.UUIDField()),
                ("refresh_token_hash", models.BinaryField(unique=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_prefix", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="replaced_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="accounts.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "indexes": [
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["user_id"],
                        name="sessions_user_active_idx",
                    ),
                    models.Index(fields=["family_id"], name="sessions_family_idx"),
                ],
            },
        ),
    ]
