# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("identity", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMFAFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(choices=[("totp", "TOTP"), ("webauthn", "WebAuthn")]),
                ),
                ("name", models.TextField()),
                ("totp_secret_ct", models.BinaryField(blank=True, null=True)),
                (
                    "credential_id",
                    models.BinaryField(blank=True, null=True, unique=True),
                ),
                ("public_key", models.BinaryField(blank=True, null=True)),
                ("sign_count", models.BigIntegerField(default=0)),
                ("aaguid", models.UUIDField(blank=True, null=True)),
                (
                    "transports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_mfa_factors",
            },
        ),
        migrations.CreateModel(
            name="UserRecoveryCode",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "code_hash",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.BinaryField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_recovery_codes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="oauthaccount",
            name="oauth_accounts_provider_provider_user_id_key",
        ),
        migrations.RemoveConstraint(
            model_name="oauthaccount",
            name="oauth_accounts_provider_check",
        ),
        migrations.AddField(
            model_name="oauthaccount",
            name="email",
            field=apps.core.fields.CIText(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="auth_method",
            field=models.TextField(
                choices=[
                    ("password", "Password"),
                    ("google", "Google"),
                    ("magic_link", "Magic Link"),
                    ("sso", "SSO"),
                    ("scim", "SCIM"),
                ],
                default="password",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="mfa_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="mfa_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="sso_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.ssoconnection",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="step_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="oauth_accounts_provider_user_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["google", "github", "microsoft"])),
                name="oauth_accounts_provider_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "auth_method__in",
                        ["password", "google", "magic_link", "sso", "scim"],
                    )
                ),
                name="sessions_auth_method_check",
            ),
        ),
        migrations.AddField(
            model_name="usermfafactor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mfa_factors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrecoverycode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="usermfafactor",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["totp", "webauthn"])),
                name="user_mfa_factors_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermfafactor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "totp"), ("totp_secret_ct__isnull", False)),
                    models.Q(
                        ("kind", "webauthn"),
                        ("credential_id__isnull", False),
                        ("public_key__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="mfa_kind_fields",
            ),
        ),
    ]
