# Generated by Django 4.2.16 on 2026-08-23 00:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_legacy_schema_compat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SsoConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("provider", models.CharField(default="saml", max_length=20)),
                ("entity_id", models.CharField(blank=True, max_length=500, null=True)),
                ("sso_url", models.TextField(blank=True, null=True)),
                ("slo_url", models.TextField(blank=True, null=True)),
                ("certificate", models.TextField(blank=True, null=True)),
                ("metadata_url", models.TextField(blank=True, null=True)),
                ("email_domains", models.TextField(blank=True, null=True)),
                ("default_role", models.CharField(default="viewer", max_length=20)),
                ("enforce_sso", models.BooleanField(default=False)),
                ("scim_enabled", models.BooleanField(default=False)),
                (
                    "scim_token_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "sso_configs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allowed_domains", models.TextField(blank=True, null=True)),
                ("blocked_domains", models.TextField(blank=True, null=True)),
                ("require_https", models.BooleanField(default=True)),
                ("require_approval", models.BooleanField(default=False)),
                ("scan_alert_threshold", models.IntegerField(default=0)),
                ("password_min_length", models.IntegerField(default=8)),
                ("session_timeout_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_policy",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "security_policies",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("condition", models.CharField(max_length=30)),
                ("operator", models.CharField(default="in", max_length=20)),
                ("value", models.TextField(blank=True, null=True)),
                ("destination_url", models.TextField()),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("hit_count", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_record",
                    models.ForeignKey(
                        db_column="qr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_rules",
                        to="api.qrrecord",
                    ),
                ),
            ],
            options={
                "db_table": "routing_rules",
                "ordering": ["-priority", "created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QRTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("design", models.JSONField(default=dict)),
                ("preview_url", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "qr_templates",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("verification_token", models.CharField(max_length=64)),
                (
                    "verification_method",
                    models.CharField(default="dns_txt", max_length=20),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("ssl_status", models.CharField(default="pending", max_length=20)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "custom_domains",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BulkJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("errors", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_jobs",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_jobs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                ("key_hash", models.CharField(max_length=255)),
                ("scopes", models.TextField(default="qr:read,qr:write,analytics:read")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("calls_today", models.BigIntegerField(default=0)),
                ("calls_reset_at", models.DateField(blank=True, null=True)),
                ("total_calls", models.BigIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_api_keys",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("color", models.CharField(default="#8B5CF6", max_length=7)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("scan_goal", models.BigIntegerField(default=0)),
                ("utm_source", models.CharField(blank=True, max_length=100, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tags", models.TextField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="api.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="campaigns_workspa_07cc3f_idx",
                    )
                ],
            },
        ),
    ]
