# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("fields", models.JSONField()),
                ("notice", models.JSONField()),
                ("notice_version", models.IntegerField(default=1)),
                ("double_opt_in", models.BooleanField(default=False)),
                ("retention_days", models.IntegerField(default=180)),
                (
                    "notify_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=apps.core.fields.CIText(), default=list
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("legacy_slug", models.TextField(blank=True, null=True, unique=True)),
                ("presentation", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "forms",
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_id", models.UUIDField()),
                ("key_id", models.IntegerField()),
                ("data_ct", models.BinaryField()),
                ("email_bidx", models.BinaryField(blank=True, null=True)),
                ("consent", models.JSONField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending_confirmation", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("withdrawn", "Withdrawn"),
                            ("erased", "Erased"),
                        ],
                        default="confirmed",
                    ),
                ),
                ("delete_after", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "form_submissions",
            },
        ),
        migrations.CreateModel(
            name="DSARRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("access", "Access"),
                            ("erasure", "Erasure"),
                            ("correction", "Correction"),
                        ]
                    ),
                ),
                ("subject_bidx", models.BinaryField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dsar_requests",
            },
        ),
    ]
