# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("orgs", "0001_initial"),
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dsarrequest",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dsar_requests",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="dsarrequest",
            name="result_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="qr.file",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="leads.form",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="qr_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_submissions",
                to="qr.qrcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="dsarrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["access", "erasure", "correction"])),
                name="dsar_requests_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="dsarrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "completed", "rejected"])),
                name="dsar_requests_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_days__gte", 1), ("retention_days__lte", 1095)),
                name="forms_retention_days_check",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["workspace_id", "-created_at"], name="form_submissions_ws_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                condition=models.Q(("email_bidx__isnull", False)),
                fields=["email_bidx"],
                name="form_submissions_bidx_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                condition=models.Q(("status", "erased"), _negated=True),
                fields=["delete_after"],
                name="form_submissions_purge_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="formsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending_confirmation", "confirmed", "withdrawn", "erased"],
                    )
                ),
                name="form_submissions_status_check",
            ),
        ),
    ]
