# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GS1Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gtin", apps.core.fields.FixedCharField(max_length=14)),
                ("cpv", models.TextField(blank=True, null=True)),
                ("lot", models.TextField(blank=True, null=True)),
                ("serial", models.TextField(blank=True, null=True)),
                ("title", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gs1_items",
                        to="qr.domain",
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gs1_items",
                        to="qr.qrcode",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gs1_items",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "gs1_items",
            },
        ),
        migrations.CreateModel(
            name="GS1Link",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link_type", models.TextField()),
                ("href", models.TextField()),
                ("title", models.TextField()),
                (
                    "hreflang",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("media_type", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="gs1.gs1item",
                    ),
                ),
            ],
            options={
                "db_table": "gs1_links",
            },
        ),
        migrations.AddIndex(
            model_name="gs1item",
            index=models.Index(fields=["domain", "gtin"], name="gs1_items_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="gs1item",
            constraint=models.CheckConstraint(
                condition=models.Q(("gtin__regex", "^[0-9]{14}$")),
                name="gs1_items_gtin_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="gs1item",
            constraint=models.UniqueConstraint(
                fields=("domain", "gtin", "cpv", "lot", "serial"),
                name="gs1_items_domain_id_gtin_cpv_lot_serial_key",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="gs1link",
            index=models.Index(fields=["item", "link_type"], name="gs1_links_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="gs1link",
            constraint=models.CheckConstraint(
                condition=models.Q(("link_type__regex", "^gs1:[A-Za-z]+$")),
                name="gs1_links_link_type_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="gs1link",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("item",),
                name="gs1_links_one_default_uniq",
            ),
        ),
    ]
