# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("slug", apps.core.fields.CIText(unique=True)),
                ("plan_id", models.TextField(default="free")),
                ("timezone", models.TextField(default="UTC")),
                ("brand", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_domain",
                    models.ForeignKey(
                        blank=True,
                        db_column="default_domain_id",
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        related_name="default_for_workspaces",
                        to="qr.domain",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workspaces",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", apps.core.fields.CIText()),
                ("role", models.TextField()),
                ("token_hash", models.BinaryField(unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invited_by",
                    models.ForeignKey(
                        db_column="invited_by",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="invites",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "invites",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "workspace",
                        "user",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="members",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_members",
            },
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan_id__in", ["free", "pro", "business", "enterprise"])),
                name="workspaces_plan_id_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["admin", "editor", "analyst"])),
                name="invites_role_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted_at__isnull", True), ("revoked_at__isnull", True)),
                fields=("workspace", "email"),
                name="invites_pending_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(fields=["user"], name="workspace_members_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["owner", "admin", "editor", "analyst"])),
                name="workspace_members_role_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("workspace",),
                name="workspace_one_owner_uniq",
            ),
        ),
    ]
