# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "__first__"),
        ("qr", "0003_remove_qrcode_qr_codes_content_type_check_and_more"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspacePolicy",
            fields=[
                (
                    "workspace",
                    models.OneToOneField(
                        db_column="workspace_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="policy",
                        serialize=False,
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "allowed_destination_hosts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                (
                    "blocked_destination_hosts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("require_https", models.BooleanField(default=True)),
                (
                    "approval_mode",
                    models.TextField(
                        choices=[
                            ("off", "Off"),
                            ("outside_allowlist", "Outside Allowlist"),
                            ("all_destination_changes", "All Destination Changes"),
                            ("all_changes", "All Changes"),
                        ],
                        default="off",
                    ),
                ),
                ("approvals_required", models.IntegerField(default=1)),
                ("approval_expiry_hours", models.IntegerField(default=168)),
                ("require_template", models.BooleanField(default=False)),
                (
                    "pixel_consent_mode",
                    models.TextField(
                        choices=[
                            ("opt_in_all", "Opt In All"),
                            ("opt_in_where_required", "Opt In Where Required"),
                        ],
                        default="opt_in_all",
                    ),
                ),
                (
                    "disabled_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "workspace_policies",
            },
        ),
        migrations.RemoveConstraint(
            model_name="invite",
            name="invites_role_check",
        ),
        migrations.RemoveConstraint(
            model_name="workspacemember",
            name="workspace_members_role_check",
        ),
        migrations.AddField(
            model_name="workspace",
            name="is_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspace",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_column="org_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces",
                to="orgs.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.TextField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("reviewer", "Reviewer"),
                    ("analyst", "Analyst"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="role",
            field=models.TextField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("reviewer", "Reviewer"),
                    ("analyst", "Analyst"),
                    ("custom", "Custom"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["org"], name="workspaces_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["admin", "editor", "reviewer", "analyst"])),
                name="invites_role_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        ["owner", "admin", "editor", "reviewer", "analyst", "custom"],
                    )
                ),
                name="workspace_members_role_check",
            ),
        ),
        migrations.AddField(
            model_name="workspacepolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "approval_mode__in",
                        [
                            "off",
                            "outside_allowlist",
                            "all_destination_changes",
                            "all_changes",
                        ],
                    )
                ),
                name="workspace_policies_approval_mode_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("approvals_required__gte", 1), ("approvals_required__lte", 3)),
                name="workspace_policies_approvals_required_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approval_expiry_hours__gte", 1),
                    ("approval_expiry_hours__lte", 720),
                ),
                name="workspace_policies_approval_expiry_hours_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pixel_consent_mode__in", ["opt_in_all", "opt_in_where_required"])
                ),
                name="workspace_policies_pixel_consent_mode_check",
            ),
        ),
    ]
