# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="workspace",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="webhooks",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="webhook",
            field=models.ForeignKey(
                db_column="webhook_id",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="deliveries",
                to="integrations.webhook",
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["workspace"],
                name="webhooks_ws_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook", "-created_at"], name="webhook_deliveries_webhook_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("webhook", "event_id"),
                name="webhook_deliveries_webhook_id_event_id_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "succeeded", "failed", "dead"])),
                name="webhook_deliveries_status_check",
            ),
        ),
    ]
