# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("zapier", "Zapier"),
                            ("make", "Make"),
                            ("hubspot", "HubSpot"),
                            ("salesforce", "Salesforce"),
                            ("google_sheets", "Google Sheets"),
                            ("ga4", "Google Analytics 4"),
                            ("warehouse_s3", "Amazon S3 Warehouse"),
                            ("warehouse_gcs", "Google Cloud Storage"),
                            ("warehouse_bigquery", "Google BigQuery"),
                        ]
                    ),
                ),
                ("name", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("credentials_ct", models.BinaryField(blank=True, null=True)),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "integrations",
            },
        ),
        migrations.CreateModel(
            name="IntegrationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "integration_deliveries",
            },
        ),
        migrations.AddField(
            model_name="webhook",
            name="signature_scheme",
            field=models.TextField(
                choices=[
                    ("standard", "Standard Webhooks"),
                    ("legacy_v1", "Legacy v1 HMAC-SHA256"),
                    ("both", "Both"),
                ],
                default="standard",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(("signature_scheme__in", ["standard", "legacy_v1", "both"])),
                name="webhooks_signature_scheme_check",
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="integrationdelivery",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="integrations.integration",
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                condition=models.Q(("status", "active")),
                fields=["workspace"],
                name="integrations_ws_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provider__in",
                        [
                            "slack",
                            "teams",
                            "zapier",
                            "make",
                            "hubspot",
                            "salesforce",
                            "google_sheets",
                            "ga4",
                            "warehouse_s3",
                            "warehouse_gcs",
                            "warehouse_bigquery",
                        ],
                    )
                ),
                name="integrations_provider_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "error", "disabled"])),
                name="integrations_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationdelivery",
            constraint=models.UniqueConstraint(
                fields=("integration", "event_id"),
                name="integration_deliveries_integration_id_event_id_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "succeeded", "failed", "dead"])),
                name="integration_deliveries_status_check",
            ),
        ),
    ]
