# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "workspaces",
            "0002_workspacepolicy_remove_invite_invites_role_check_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "frequency",
                    models.TextField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ]
                    ),
                ),
                ("weekday", models.IntegerField(blank=True, null=True)),
                ("month_day", models.IntegerField(blank=True, null=True)),
                ("hour_local", models.IntegerField(default=9)),
                ("timezone", models.TextField()),
                ("filters", models.JSONField(default=dict)),
                (
                    "format",
                    models.TextField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("both", "Both")],
                        default="pdf",
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(base_field=apps.core.fields.CIText()),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "report_schedules",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["next_run_at"],
                        name="report_schedules_due_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("frequency__in", ["daily", "weekly", "monthly"])),
                        name="report_schedules_frequency_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weekday__isnull", True),
                            models.Q(("weekday__gte", 1), ("weekday__lte", 7)),
                            _connector="OR",
                        ),
                        name="report_schedules_weekday_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("month_day__isnull", True),
                            models.Q(("month_day__gte", 1), ("month_day__lte", 28)),
                            _connector="OR",
                        ),
                        name="report_schedules_month_day_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("hour_local__gte", 0), ("hour_local__lte", 23)),
                        name="report_schedules_hour_local_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("format__in", ["pdf", "csv", "both"])),
                        name="report_schedules_format_check",
                    ),
                ],
            },
        ),
    ]
