# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids
import apps.orgs.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("slug", apps.core.fields.CIText(unique=True)),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("personal", "Personal"),
                            ("standard", "Standard"),
                            ("enterprise", "Enterprise"),
                            ("agency", "Agency"),
                        ],
                        default="standard",
                    ),
                ),
                (
                    "plan_id",
                    models.TextField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                    ),
                ),
                (
                    "data_region",
                    models.TextField(
                        choices=[
                            ("in", "India"),
                            ("eu", "Europe"),
                            ("us", "United States"),
                        ],
                        default="in",
                    ),
                ),
                ("legal_name", models.TextField(blank=True, null=True)),
                ("billing_email", apps.core.fields.CIText(blank=True, null=True)),
                ("gstin", models.TextField(blank=True, null=True)),
                (
                    "tax_country",
                    apps.core.fields.FixedCharField(default="IN", max_length=2),
                ),
                ("billing_address", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("billing_hold_since", models.DateTimeField(blank=True, null=True)),
                ("grandfathered_limits", models.JSONField(default=dict)),
                (
                    "parent_org",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_org_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_orgs",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="OrgDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", apps.core.fields.CIText()),
                ("verification_token", models.TextField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("auto_join", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "auto_join_workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "db_table": "org_domains",
            },
        ),
        migrations.CreateModel(
            name="OrgMember",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "org",
                        "user",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_role",
                    models.TextField(
                        choices=[
                            ("org_owner", "Org Owner"),
                            ("org_admin", "Org Admin"),
                            ("billing_admin", "Billing Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deprovisioned", "Deprovisioned"),
                        ],
                        default="active",
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("invite", "Invite"),
                            ("sso_jit", "SSO JIT"),
                            ("scim", "SCIM"),
                            ("creator", "Creator"),
                        ],
                        default="invite",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="orgs.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "org_members",
            },
        ),
        migrations.CreateModel(
            name="OrgSecurityPolicy",
            fields=[
                (
                    "org",
                    models.OneToOneField(
                        db_column="org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="security_policy",
                        serialize=False,
                        to="orgs.organization",
                    ),
                ),
                ("enforce_sso", models.BooleanField(default=False)),
                (
                    "sso_break_glass_user_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list
                    ),
                ),
                ("require_mfa", models.BooleanField(default=False)),
                (
                    "allowed_mfa_kinds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        default=apps.orgs.models.default_allowed_mfa,
                    ),
                ),
                ("session_idle_minutes", models.IntegerField(default=0)),
                ("session_max_hours", models.IntegerField(default=0)),
                (
                    "dashboard_ip_allowlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=apps.core.fields.CIDRField(), default=list
                    ),
                ),
                (
                    "api_ip_allowlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=apps.core.fields.CIDRField(), default=list
                    ),
                ),
                ("password_min_length", models.IntegerField(default=10)),
                (
                    "invite_email_domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=apps.core.fields.CIText(), default=list
                    ),
                ),
                ("api_key_max_days", models.IntegerField(default=0)),
                (
                    "export_permission",
                    models.TextField(
                        choices=[
                            ("role", "Role"),
                            ("admins_only", "Admins Only"),
                            ("disabled", "Disabled"),
                        ],
                        default="role",
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "org_security_policies",
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                condition=models.Q(("parent_org__isnull", False)),
                fields=["parent_org"],
                name="organizations_parent_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["personal", "standard", "enterprise", "agency"])),
                name="organizations_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan_id__in", ["free", "pro", "business", "enterprise"])),
                name="organizations_plan_id_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_region__in", ["in", "eu", "us"])),
                name="organizations_data_region_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gstin__isnull", True),
                    (
                        "gstin__regex",
                        "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$",
                    ),
                    _connector="OR",
                ),
                name="organizations_gstin_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_org__isnull", True),
                    models.Q(("parent_org", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="org_no_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgdomain",
            constraint=models.UniqueConstraint(
                fields=("org", "domain"), name="org_domains_org_domain_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="orgdomain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("verified_at__isnull", False)),
                fields=("domain",),
                name="org_domains_verified_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="orgmember",
            index=models.Index(fields=["user"], name="org_members_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "org_role__in",
                        ["org_owner", "org_admin", "billing_admin", "member"],
                    )
                ),
                name="org_members_org_role_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "suspended", "deprovisioned"])),
                name="org_members_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["invite", "sso_jit", "scim", "creator"])),
                name="org_members_source_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org_role", "org_owner")),
                fields=("org",),
                name="org_one_owner_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgsecuritypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session_idle_minutes", 0),
                    models.Q(
                        ("session_idle_minutes__gte", 5),
                        ("session_idle_minutes__lte", 10080),
                    ),
                    _connector="OR",
                ),
                name="org_security_policies_session_idle_minutes_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgsecuritypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("session_max_hours", 0),
                    models.Q(("session_max_hours__gte", 1), ("session_max_hours__lte", 2160)),
                    _connector="OR",
                ),
                name="org_security_policies_session_max_hours_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgsecuritypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("password_min_length__gte", 10), ("password_min_length__lte", 128)
                ),
                name="org_security_policies_password_min_length_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgsecuritypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("api_key_max_days__gte", 0)),
                name="org_security_policies_api_key_max_days_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgsecuritypolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("export_permission__in", ["role", "admins_only", "disabled"])),
                name="org_security_policies_export_permission_check",
            ),
        ),
    ]
