# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids
import apps.serials.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "gtin",
                    apps.core.fields.FixedCharField(blank=True, max_length=14, null=True),
                ),
                ("quantity", models.IntegerField()),
                (
                    "rules",
                    models.JSONField(default=apps.serials.models.default_serial_rules),
                ),
                ("verify_page", models.JSONField(default=dict)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("void", "Void"),
                        ],
                        default="generating",
                    ),
                ),
                ("generated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serial_batch",
                        to="qr.qrcode",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_batches",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "serial_batches",
            },
        ),
        migrations.CreateModel(
            name="SerialCode",
            fields=[
                (
                    "serial",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("flagged", "Flagged"),
                            ("void", "Void"),
                        ],
                        default="active",
                    ),
                ),
                ("scan_count", models.IntegerField(default=0)),
                ("first_scan_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_country",
                    apps.core.fields.FixedCharField(blank=True, max_length=2, null=True),
                ),
                ("first_city", models.TextField(blank=True, null=True)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=apps.core.fields.FixedCharField(max_length=2),
                        default=list,
                    ),
                ),
                ("flagged_reason", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="serials.serialbatch",
                    ),
                ),
            ],
            options={
                "db_table": "serial_codes",
            },
        ),
        migrations.AddConstraint(
            model_name="serialbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gtin__isnull", True),
                    ("gtin__regex", "^[0-9]{14}$"),
                    _connector="OR",
                ),
                name="serial_batches_gtin_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 10000000)),
                name="serial_batches_quantity_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["generating", "ready", "void"])),
                name="serial_batches_status_check",
            ),
        ),
        migrations.AddIndex(
            model_name="serialcode",
            index=models.Index(fields=["batch", "status"], name="serial_codes_batch_idx"),
        ),
        migrations.AddConstraint(
            model_name="serialcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("serial__regex", "^[0-9A-HJKMNP-TV-Z]{12}$")),
                name="serial_codes_serial_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="serialcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "flagged", "void"])),
                name="serial_codes_status_check",
            ),
        ),
    ]
