# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("developer", "0001_initial"),
        ("qr", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="workspace",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="api_keys",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.DB_SET_NULL,
                related_name="created_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="input_file",
            field=models.ForeignKey(
                blank=True,
                db_column="input_file_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="input_for_jobs",
                to="qr.file",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="output_file",
            field=models.ForeignKey(
                blank=True,
                db_column="output_file_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="output_for_jobs",
                to="qr.file",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="workspace",
            field=models.ForeignKey(
                db_column="workspace_id",
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="jobs",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=["workspace"],
                name="api_keys_ws_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["workspace", "-created_at"], name="jobs_ws_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "bulk_create",
                            "export_scans",
                            "export_qr_codes",
                            "bulk_download",
                        ],
                    )
                ),
                name="jobs_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["queued", "running", "succeeded", "failed", "canceled"],
                    )
                ),
                name="jobs_status_check",
            ),
        ),
    ]
