# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("developer", "0002_initial"),
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUsageDaily",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "api_key_id",
                        "day",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_key_id", models.UUIDField()),
                ("day", models.DateField()),
                ("requests", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("throttled", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "api_usage_daily",
            },
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="jobs_kind_check",
        ),
        migrations.AddField(
            model_name="apikey",
            name="environment",
            field=models.TextField(choices=[("live", "Live"), ("test", "Test")], default="live"),
        ),
        migrations.AddField(
            model_name="apikey",
            name="ip_allowlist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=apps.core.fields.CIDRField(), default=list
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="legacy_bcrypt_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="legacy_kind",
            field=models.TextField(
                blank=True,
                choices=[("v1_user", "v1 User"), ("v1_workspace", "v1 Workspace")],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment__in", ["live", "test"])),
                name="api_keys_environment_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("legacy_kind__isnull", True),
                    ("legacy_kind__in", ["v1_user", "v1_workspace"]),
                    _connector="OR",
                ),
                name="api_keys_legacy_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "bulk_create",
                            "bulk_update",
                            "bulk_download",
                            "export_scans",
                            "export_qr_codes",
                            "print_sheet",
                            "serial_generate",
                            "serial_export",
                            "gs1_import",
                            "warehouse_export",
                            "audit_export",
                            "dsar_export",
                            "lead_export",
                            "report_run",
                        ],
                    )
                ),
                name="jobs_kind_check",
            ),
        ),
    ]
