# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids
import apps.identity.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SCIMUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.TextField(blank=True, null=True)),
                ("user_name", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("resource", models.JSONField()),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "scim_users",
            },
        ),
        migrations.CreateModel(
            name="SSOConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "protocol",
                    models.TextField(choices=[("saml", "SAML"), ("oidc", "OIDC")]),
                ),
                ("label", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("draft", "Draft"),
                            ("testing", "Testing"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                    ),
                ),
                ("bridge_tenant", models.TextField(blank=True, null=True)),
                ("oidc_issuer", models.TextField(blank=True, null=True)),
                ("oidc_client_id", models.TextField(blank=True, null=True)),
                ("oidc_client_secret_ct", models.BinaryField(blank=True, null=True)),
                ("jit_provisioning", models.BooleanField(default=True)),
                ("default_role_key", models.TextField(default="analyst")),
                (
                    "attribute_mapping",
                    models.JSONField(default=apps.identity.models.default_attribute_mapping),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("oidc_scopes", models.TextField(default="openid email profile")),
                ("groups_claim", models.TextField(default="groups")),
                ("test_passed_at", models.DateTimeField(blank=True, null=True)),
                ("saml_metadata_url", models.TextField(blank=True, null=True)),
                (
                    "idp_kind",
                    models.TextField(
                        choices=[
                            ("okta", "Okta"),
                            ("entra", "Entra ID"),
                            ("google", "Google Workspace"),
                            ("jumpcloud", "JumpCloud"),
                            ("onelogin", "OneLogin"),
                            ("ping", "Ping Identity"),
                            ("keycloak", "Keycloak"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                    ),
                ),
            ],
            options={
                "db_table": "sso_connections",
            },
        ),
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.TextField()),
                ("email_at_login", apps.core.fields.CIText()),
                ("raw_claims", models.JSONField(default=dict)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "user_identities",
            },
        ),
        migrations.CreateModel(
            name="SCIMDirectory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.TextField()),
                ("token_prefix", models.TextField(unique=True)),
                ("token_hash", models.BinaryField(unique=True)),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                    ),
                ),
                (
                    "deprovision_action",
                    models.TextField(
                        choices=[("suspend", "Suspend"), ("remove", "Remove")],
                        default="suspend",
                    ),
                ),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scim_directories",
            },
        ),
    ]
