# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("orgs", "0001_initial"),
        (
            "workspaces",
            "0002_workspacepolicy_remove_invite_invites_role_check_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scimdirectory",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scim_directories",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="scimuser",
            name="directory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="identity.scimdirectory",
            ),
        ),
        migrations.AddField(
            model_name="scimuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scim_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="default_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_connections",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="useridentity",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to="identity.ssoconnection",
            ),
        ),
        migrations.AddField(
            model_name="useridentity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="scimdirectory",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "disabled"])),
                name="scim_directories_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="scimdirectory",
            constraint=models.CheckConstraint(
                condition=models.Q(("deprovision_action__in", ["suspend", "remove"])),
                name="scim_directories_deprovision_action_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="scimuser",
            constraint=models.UniqueConstraint(
                fields=("directory", "user_name"),
                name="scim_users_directory_id_user_name_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="scimuser",
            constraint=models.UniqueConstraint(
                fields=("directory", "user"), name="scim_users_directory_id_user_id_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="scimuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("directory", "external_id"),
                name="scim_users_external_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="ssoconnection",
            index=models.Index(fields=["org"], name="sso_connections_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="ssoconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("protocol__in", ["saml", "oidc"])),
                name="sso_connections_protocol_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ssoconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "testing", "active", "disabled"])),
                name="sso_connections_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ssoconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("protocol", "oidc"), _negated=True),
                    models.Q(
                        ("oidc_issuer__isnull", False),
                        ("oidc_client_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sso_oidc_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="ssoconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "idp_kind__in",
                        [
                            "okta",
                            "entra",
                            "google",
                            "jumpcloud",
                            "onelogin",
                            "ping",
                            "keycloak",
                            "custom",
                        ],
                    )
                ),
                name="sso_connections_idp_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="useridentity",
            constraint=models.UniqueConstraint(
                fields=("connection", "subject"),
                name="user_identities_connection_id_subject_key",
            ),
        ),
    ]
