# Generated by Django 6.1.1 on 2026-10-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.fields
import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", apps.core.fields.CIText(unique=True)),
                ("status", models.TextField(default="pending")),
                ("verification_token", models.TextField()),
                ("provider_hostname_id", models.TextField(blank=True, null=True)),
                ("tls_status", models.TextField(default="pending")),
                ("root_redirect_url", models.TextField(blank=True, null=True)),
                ("not_found_url", models.TextField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "domains",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purpose", models.TextField()),
                ("storage_key", models.TextField(unique=True)),
                ("mime_type", models.TextField()),
                ("size_bytes", models.BigIntegerField()),
                ("sha256", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "files",
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "folders",
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mode", models.TextField()),
                ("content_type", models.TextField()),
                ("name", models.TextField()),
                ("short_code", models.TextField(blank=True, null=True)),
                ("legacy_short_code", models.TextField(blank=True, null=True)),
                (
                    "gs1_gtin",
                    apps.core.fields.FixedCharField(blank=True, max_length=14, null=True),
                ),
                ("static_payload", models.TextField(blank=True, null=True)),
                ("static_content", models.JSONField(blank=True, null=True)),
                ("design", models.JSONField(default=dict)),
                ("design_hash", models.BinaryField(blank=True, null=True)),
                ("status", models.TextField(default="active")),
                ("is_read_only", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scan_limit", models.BigIntegerField(blank=True, null=True)),
                ("password_hash", models.TextField(blank=True, null=True)),
                ("fallback_url", models.TextField(blank=True, null=True)),
                ("safety_status", models.TextField(default="pending")),
                ("total_scans", models.BigIntegerField(default=0)),
                ("unique_scans", models.BigIntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "qr_codes",
            },
        ),
        migrations.CreateModel(
            name="QRCodeTag",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "qr_code",
                        "tag",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "qr_code_tags",
            },
        ),
        migrations.CreateModel(
            name="QRVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_no", models.IntegerField()),
                ("destination_kind", models.TextField()),
                ("destination_url", models.TextField(blank=True, null=True)),
                ("hosted_page", models.JSONField(blank=True, null=True)),
                ("rules", models.JSONField(default=list)),
                ("utm", models.JSONField(default=dict)),
                (
                    "effective_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("safety_status", models.TextField(default="pending")),
                ("change_note", models.TextField(blank=True, null=True)),
                ("created_by_key", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "qr_versions",
            },
        ),
        migrations.CreateModel(
            name="ShortCodeTombstone",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "domain",
                        "short_code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("short_code", models.TextField()),
                ("purged_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "short_code_tombstones",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", apps.core.fields.CIText()),
                ("color", models.TextField(default="#64748B")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("design", models.JSONField()),
                ("is_locked", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "templates",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("status", models.TextField(default="active")),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("goal_scans", models.BigIntegerField(blank=True, null=True)),
                ("utm", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
    ]
