# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "__first__"),
        ("qr", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="qrcode",
            name="qr_codes_content_type_check",
        ),
        migrations.RemoveConstraint(
            model_name="qrcode",
            name="qr_static_types",
        ),
        migrations.AddField(
            model_name="qrcode",
            name="legacy_host",
            field=apps.core.fields.CIText(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="needs_reprint",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="v1_printed_payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qrversion",
            name="approval_request",
            field=models.ForeignKey(
                blank=True,
                db_column="approval_request_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="approvals.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="qrversion",
            name="approval_status",
            field=models.TextField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_required",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                condition=models.Q(("legacy_short_code__isnull", False)),
                fields=["legacy_host", "legacy_short_code"],
                name="qr_codes_legacy_host_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qrversion",
            index=models.Index(
                condition=models.Q(("approval_status", "pending")),
                fields=["qr_code"],
                name="qr_versions_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qrversion",
            index=models.Index(
                condition=models.Q(("approval_request__isnull", False)),
                fields=["approval_request"],
                name="qr_versions_approval_req_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "content_type__in",
                        [
                            "url",
                            "text",
                            "email",
                            "phone",
                            "sms",
                            "whatsapp",
                            "wifi",
                            "vcard",
                            "event",
                            "upi",
                            "location",
                            "links_page",
                            "file",
                            "app_store",
                            "gs1",
                            "form",
                            "serial_batch",
                        ],
                    )
                ),
                name="qr_codes_content_type_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode", "dynamic"),
                    models.Q(
                        (
                            "content_type__in",
                            [
                                "links_page",
                                "file",
                                "app_store",
                                "gs1",
                                "form",
                                "serial_batch",
                            ],
                        ),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="qr_static_types",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "approval_status__in",
                        [
                            "not_required",
                            "pending",
                            "approved",
                            "rejected",
                            "cancelled",
                        ],
                    )
                ),
                name="qr_versions_approval_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approval_status__in", ["pending", "approved", "rejected"]),
                        _negated=True,
                    ),
                    ("approval_request__isnull", False),
                    _connector="OR",
                ),
                name="qr_version_pending_has_request",
            ),
        ),
    ]
