# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.TextField()),
                (
                    "source",
                    models.TextField(
                        choices=[
                            ("manual", "Manual"),
                            ("scim", "SCIM"),
                            ("sso", "SSO"),
                        ],
                        default="manual",
                    ),
                ),
                ("external_id", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "group_id",
                        "user_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(default="")),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField()),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "principal_type",
                    models.TextField(choices=[("user", "User"), ("group", "Group")]),
                ),
                ("principal_id", models.UUIDField()),
                (
                    "scope_type",
                    models.TextField(
                        choices=[("workspace", "Workspace"), ("folder", "Folder")],
                        default="workspace",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "role_bindings",
            },
        ),
    ]
