# Generated by Django 6.1.1 on 2026-10-03 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0002_initial"),
        ("orgs", "0001_initial"),
        ("qr", "0003_remove_qrcode_qr_codes_content_type_check_and_more"),
        (
            "workspaces",
            "0002_workspacepolicy_remove_invite_invites_role_check_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="orgs.organization",
            ),
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "group",
                        "user",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="access.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_roles",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="rolebinding",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rolebinding",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_bindings",
                to="qr.folder",
            ),
        ),
        migrations.AddField(
            model_name="rolebinding",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="orgs.organization",
            ),
        ),
        migrations.AddField(
            model_name="rolebinding",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bindings",
                to="access.role",
            ),
        ),
        migrations.AddField(
            model_name="rolebinding",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_bindings",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["org", "source"], name="groups_org_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["manual", "scim", "sso"])),
                name="groups_source_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("org", "display_name"), name="groups_org_id_display_name_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "scim"), ("directory__isnull", False)),
                    models.Q(
                        models.Q(("source", "scim"), _negated=True),
                        ("directory__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="group_scim_dir",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(fields=["user"], name="group_members_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(("key__regex", "^[a-z][a-z0-9_]{1,40}$")),
                name="roles_key_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("org", "key"), name="roles_org_id_key_key", nulls_distinct=False
            ),
        ),
        migrations.AddIndex(
            model_name="rolebinding",
            index=models.Index(
                fields=["principal_type", "principal_id"],
                name="role_bindings_principal_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rolebinding",
            index=models.Index(fields=["workspace"], name="role_bindings_ws_idx"),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("principal_type__in", ["user", "group"])),
                name="role_bindings_principal_type_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_type__in", ["workspace", "folder"])),
                name="role_bindings_scope_type_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope_type", "folder"), ("folder__isnull", False)),
                    models.Q(("scope_type", "workspace"), ("folder__isnull", True)),
                    _connector="OR",
                ),
                name="binding_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.UniqueConstraint(
                fields=(
                    "workspace",
                    "principal_type",
                    "principal_id",
                    "role",
                    "folder",
                ),
                name="role_bindings_workspace_id_principal_type_principal_id_role_key",
                nulls_distinct=False,
            ),
        ),
    ]
